### ISSUE TITLE
Build arm64 binaries to run on Raspbian OS

### ISSUE THREAD

**Issue by muratkars** [openebs/openebs#1295] opened 2018-02-28 18:53 UTC
Usecase: Highly available ownCloud running on Kubernetes cluster

Raspberry Pi 3 model b is cost & power efficient to run ownCloud, but the issue is neither storage nor the nodes can be configured as HA. 
I'm running ownCloud on 6 nodes Kubernetes cluster on Raspbian Lite, application availability is achieved, but i can't protect my storage since there is only single SSD attached to each node.
I want to try OpenEBS to see if I can achieve storage availability by replicating with OpenEBS.
Use case is niche and unproven since the resources on Raspberry Pi 3 is limited. OpenFaaS is another common usecase popular on Raspberry. 

My cluster specs:
6 nodes K8s cluster running on Raspbian Lite
Each node:
Quad Core 1.2GHz Broadcom BCM2837 64bit CPU
1GB RAM
32 GB SD for OS
512 GB SSD for data

**Comment by muratkars** [comment] 2018-03-29 16:45
Quick update for arm64 enthusiasts:
Made some progress here fixing dependencies and building deps for arm64 architecture. Instead of RPi 3 I've used a little bit more powerful SoC called [Le Potato](https://libre.computer/products/boards/aml-s905x-cc/) from Libre Computer.
Need more testing, and integration with OpenEBS build setup before I can send a PR, but in the meantime if you want to play with it, my images are [here](https://hub.docker.com/u/muratkarslioglu/)

**Comment by muratkars** [comment] 2018-04-06 22:16
My request to get a CI setup hw from WorksOnArm Project is approved.
https://github.com/WorksOnArm/cluster/issues/54

Next week I am hoping to spend some time with OpenEBS build team to unify amd64 and arm64 builds and get official builds started.

**Comment by jmreicha** [comment] 2018-06-07 05:48
Any update on this?  I'm working on an ARM cluster for my home lab and would love to get a storage solution like OpenEBS working.

**Comment by vielmetti** [comment] 2018-06-20 13:00
Hi @muratkars @jmreicha I'm hopeful that there's an update here - let me know if there's anything I can do to help from the arm64 cluster side at Packet.

**Comment by muratkars** [comment] 2018-06-20 14:24
Hi @vielmetti @jmreicha - Team is working on this. Currently, build and instructions provided [here](https://blog.openebs.io/arming-kubernetes-with-openebs-1-b450f41e0c1f) seems to be functional. 
Once the 0.6 release is out, a new arm64 build will be released and we will focus back on getting it into CI run on packet and adding few more validation steps for arm64.

**Comment by vielmetti** [comment] 2018-06-20 14:59
Thanks @muratkars ! Remind me what your CI infrastructure looks like? I want to make sure we have the right sort of resources ready.

**Comment by jmreicha** [comment] 2018-10-01 16:45
@muratkars Can you point me in the right direction for how/where builds happen?  I'd like to take see if I can take a stab at this as part of Octoberfest.

**Comment by andrei-dascalu** [comment] 2019-03-02 21:47
@muratkars Hello!

I see this is still open and the issue also interests me a lot as I'm working on a k8s cluster on Rock64 boards.
I've tried the instructions at https://blog.openebs.io/arming-kubernetes-with-openebs-1-b450f41e0c1f but it looks like the yml provided aren't available anymore. 
Is there something I can do to help with this?

Cheers!

**Comment by muratkars** [comment] 2019-03-02 22:36
Thanks @andrei-dascalu . Team is working to get automation of multi-architecture images up soon. In the meantime, I'll try to get the v0.8.1 arm64 built this week and update the issue here. cc @harshvkarn

**Comment by bwolf** [comment] 2019-03-08 06:38
@muratkars Anything new for us waiting for arm64? I'm curious to give OpenEBS a try on my cluster!

**Comment by kmova** [comment] 2019-03-13 15:24
Thanks @bwolf for checking back on this. Added this for 0.9.

**Comment by dewet22** [comment] 2019-07-14 14:11
@muratkars worth asking about another update? This seems to be slipping without any resolution in sight. With the new RPi4 and other more powerful SBCs using arm64 being available now, this is quite a limitation to wider adoption.

**Comment by harshvkarn** [comment] 2019-07-15 07:59
@dewet22 This wasn't on the highly active issue until now :) Builds will be coming soon. I'll keep this issue posted. Thanks.

**Comment by DeanHao** [comment] 2019-08-09 10:34
yaml files https://raw.githubusercontent.com/muratkars/openebs/lepotato-arm64/k8s/openebs-operator-arm64.yaml & https://raw.githubusercontent.com/muratkars/openebs/lepotato-arm64/k8s/openebs-storageclasses.yaml no longer appear to be present. Is there any update on the arm64 builds?

**Comment by vielmetti** [comment] 2019-08-26 11:52
@harshvkarn is there an update on this? Thanks!

**Comment by harshvkarn** [comment] 2019-08-26 15:02
@vielmetti 
We were able to build the bare minimum OpenEBS w/ Jiva. I will commit for the official build process very soon.
These are the images for now if you want to test it.
```
harshvkarn/jiva:arm
harshvkarn/provisioner-localpv:alpine-arm64
harshvkarn/admission-server:arm
harshvkarn/m-apiserver:arm
harshvkarn/node-disk-manager:arm
harshvkarn/node-disk-operator:arm
harshvkarn/openebs-k8s-provisioner:arm
```

**Comment by Cerebus** [comment] 2019-09-11 01:36
Attempting a deploy in k3s on RPI3B running Ubuntu 18.04.3/aarch64, maya-apiserver dumps out in preflight:
```
$ kubectl logs maya-apiserver-5d9b995c9-r6nvz
+ MAYA_API_SERVER_NETWORK=eth0
+ grep inet
+ awk {print $2}
+ ip -4 addr show scope global dev eth0
+ cut -d / -f 1
+ CONTAINER_IP_ADDR=10.42.1.5
+ exec /usr/local/bin/maya-apiserver start --bind=10.42.1.5
I0911 01:22:01.742542       6 start.go:153] Initializing maya-apiserver...
preflight checks failed:   --  precheck for bdc failed: the server could not find the requested resource (get blockdeviceclaims.openebs.io)
````
I could be missing something obvious, so feel free to point out what I could be doing wrong.  :)

-- T

**Comment by Cerebus** [comment] 2019-09-14 04:37
@harshvkarn Redeployed k8s 1.15.3 w/ kubeadm on ubuntu 18.04/aarch64, .  maya-apiserver errors our the same as k3s above (same platform).  
ndm-operator errors out:
```
{"level":"info","ts":1568435605.2400267,"logger":"ndm-operator","msg":"Go Version: go1.12.5"}
{"level":"info","ts":1568435605.240167,"logger":"ndm-operator","msg":"Go OS/Arch: linux/arm64"}
{"level":"info","ts":1568435605.2402081,"logger":"ndm-operator","msg":"operator-sdk Version: v0.5.0"}
{"level":"info","ts":1568435605.2474062,"logger":"leader","msg":"Trying to become the leader."}
{"level":"info","ts":1568435605.8234258,"logger":"leader","msg":"Found existing lock with my name. I was likely restarted."}
{"level":"info","ts":1568435605.8236134,"logger":"leader","msg":"Continuing as the leader."}
{"level":"info","ts":1568435606.252126,"logger":"ndm-operator","msg":"Registering Components"}
{"level":"info","ts":1568435606.2535322,"logger":"kubebuilder.controller","msg":"Starting EventSource","controller":"blockdevice-controller","source":"kind source: /, Kind="}
{"level":"error","ts":1568435606.2538614,"logger":"kubebuilder.source","msg":"if kind is a CRD, it should be installed before calling Start","kind":"BlockDevice.openebs.io","error":"no matches for kind \"BlockDevice\" in version \"openebs.io/v1alpha1\"","stacktrace":"github.com/openebs/node-disk-manager/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/root/go/src/github.com/openebs/node-disk-manager/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/openebs/node-disk-manager/vendor/sigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start\n\t/root/go/src/github.com/openebs/node-disk-manager/vendor/sigs.k8s.io/controller-runtime/pkg/source/source.go:89\ngithub.com/openebs/node-disk-manager/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Watch\n\t/root/go/src/github.com/openebs/node-disk-manager/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:122\ngithub.com/openebs/node-disk-manager/pkg/controller/blockdevice.add\n\t/root/go/src/github.com/openebs/node-disk-manager/pkg/controller/blockdevice/blockdevice_controller.go:53\ngithub.com/openebs/node-disk-manager/pkg/controller/blockdevice.Add\n\t/root/go/src/github.com/openebs/node-disk-manager/pkg/controller/blockdevice/blockdevice_controller.go:36\ngithub.com/openebs/node-disk-manager/pkg/controller.AddToManager\n\t/root/go/src/github.com/openebs/node-disk-manager/pkg/controller/controller.go:13\nmain.main\n\t/root/go/src/github.com/openebs/node-disk-manager/cmd/manager/main.go:88\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:200"}
{"level":"error","ts":1568435606.2542424,"logger":"ndm-operator","msg":"","error":"no matches for kind \"BlockDevice\" in version \"openebs.io/v1alpha1\"","stacktrace":"github.com/openebs/node-disk-manager/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/root/go/src/github.com/openebs/node-disk-manager/vendor/github.com/go-logr/zapr/zapr.go:128\nmain.main\n\t/root/go/src/github.com/openebs/node-disk-manager/cmd/manager/main.go:89\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:200"}
```
FWIW, ndm-operator gives the same error on k3s, so damnfino what the problem is.  Any help?

-- T

**Comment by Cerebus** [comment] 2019-09-14 15:30
Seems to be working with these images:
```
harshvkarn/m-apiserver:arm
harshvkarn/openebs-k8s-provisioner:arm
harshvkarn/node-disk-manager-arm64:v0.4.1
harshvkarn/node-disk-operator-arm64:v0.4.1
harshvkarn/admission-server:arm
harshvkarn/provisioner-localpv:alpine-arm64
```
By "working" I mean all the pods come up, and all the expected CRDs are registered.  I'll burn it all down again and repeat on k3s.  (Bob bless Ansible developers. :)

-- T

**Comment by kmova** [comment] 2019-09-14 16:07
@Cerebus @DeanHao thanks for using and verifying with the above images. Taking this up for 1.3 release to make setup travis builds and generate images.

**Comment by Cerebus** [comment] 2019-09-14 23:25
Working on k3s as well, to the same level as before.  I haven't yet tried deploying a storage backed workload.  :)

**Comment by vielmetti** [comment] 2019-09-16 19:56
Hi @muratkars - what is the prognosis on getting support for arm64 released? Arm Techcon is coming up, would be lovely to have some announcement synced by then. (I don't see a due date for the 1.3 milestone, so I don't know what your expected time frame is at all.)

**Comment by kmova** [comment] 2019-09-17 03:20
@vielmetti - tentatively planned for 2nd week of october, we are on monthly cadence.  Are you referring to oct 8-10 techcon?

**Comment by muratkars** [comment] 2019-10-02 16:29
Just a quick update here an many thanks to @DeanHao for contributions, @vielmetti and community being patient with us. 
Although manual builds were possible and done by the community members and me and in the past (quick Docker Hub [search](https://hub.docker.com/search?q=openebs&type=image&architecture=arm64) shows that) automating multi-architectural builds for key OpenEBS container images took a little bit longer than we anticipated. 
Target release is still 1.3 and we are very close to deliver it this time.

**Comment by radicand** [comment] 2019-10-19 14:14
Are there updated images available for use now, even if just in testing at this stage? I'm looking forward to arm64 support for my home lab and would be interested in helping sanity test.

**Comment by AmitKumarDas** [comment] 2019-10-19 14:34
@radicand thanks for your interest. Do look out relevant Dockerfiles in this location

https://github.com/openebs/maya/tree/master/buildscripts

**Comment by radicand** [comment] 2019-11-09 13:43
Thanks @AmitKumarDas , I was hoping there would be a published image to use for testing vs. building one; but I've looked at the repo without much luck on determining how to build it myself. It appears to need some binaries built before the docker image can be built, and I have not been successful with determining how to do this yet. Any guidance (or links to where images may already exist) would be appreciated.

**Comment by AmitKumarDas** [comment] 2019-11-09 13:53
@radicand Let me get back with proper links/contributors. Do you mind connecting us on openebs slack for quicker response/discussions?

**Comment by EpiqSty** [comment] 2019-11-15 08:19
Sorry for the offtopic, but is there any chance to get openebs running on armhf(or armv7l ) architecture?
 Thanks in advance for any information!

**Comment by kmova** [comment] 2019-11-15 08:24
I am working on a document that explains how to build the binaries and will get it out for the 1.14 release. A short summary is that local pv and jiva volumes related containers can now be built on arm machines.

**Comment by kmova** [comment] 2019-11-17 14:05
Sample YAML for installing OpenEBS using the images built for arm64 is here:

https://github.com/openebs/charts/blob/master/docs/openebs-operator-arm-dev.yaml

Looking for help from community to test these images and provide us a list of issues/enhancements. Please comment her e or join our Slack arm channel.

**Comment by Guigouu** [comment] 2019-12-06 16:32
@kmova Thank you a lot ! Additionally for jiva volume, we need two more containers:
- The pvc controller require maya-exporter arm64 container, which is currently possible by building the source code openbs/slp openebs/libcstor openebs/cstor to have the arm64 base image and finally build via openebs/maya the m-exporter.
- The ScrubJob needs also openebs-tools arm64  to propagate the deletion.

**Comment by kmova** [comment] 2019-12-26 18:22
@Guigouu -- thanks for reporting the issue with the jiva scrub image. Fixed maya to override the scrub image using the IO_HELPER_IMAGE env. 

The exporter image will be fixed in 1.6, along with the support for cstor arm builds.

**Comment by carnei-ro** [comment] 2020-01-02 15:33
is it live? how do I install?  https://raw.githubusercontent.com/muratkars/openebs/lepotato-arm64/k8s/openebs-operator-arm64.yaml is not working anymore :(

**Comment by kmova** [comment] 2020-01-02 15:42
@carnei-ro - can you try this? https://github.com/openebs/charts/blob/master/docs/openebs-operator-arm-dev.yaml.

**Comment by carnei-ro** [comment] 2020-01-02 17:04
@kmova it kinda works, when I create the StoragePoolClaim, it launches cstor-pool, cstor-pool-mgmt and m-exporter, but as x86_64 I think. Should I try to use Jiva? Are there any docs?

**Comment by carnei-ro** [comment] 2020-01-02 17:34
I've edited the yaml and now it seems to work. Thanks
```
        - name: OPENEBS_IO_CSTOR_TARGET_IMAGE
          value: "mayankrpatel/cstor-istgt:arm-ci"
        - name: OPENEBS_IO_CSTOR_POOL_IMAGE
          value: "mayankrpatel/cstor-pool:arm-ci"
        - name: OPENEBS_IO_CSTOR_POOL_MGMT_IMAGE
          value: "mayankrpatel/cstor-pool-mgmt:arm-ci"
        - name: OPENEBS_IO_CSTOR_VOLUME_MGMT_IMAGE
          value: "quay.io/openebs/cstor-volume-mgmt:1.5.0"
        - name: OPENEBS_IO_VOLUME_MONITOR_IMAGE
          value: "goaoza/m-exporter-arm64"
        - name: OPENEBS_IO_CSTOR_POOL_EXPORTER_IMAGE
          value: "goaoza/m-exporter-arm64"
```

**Comment by kmova** [comment] 2020-01-02 18:28
I haven't yet tested the cstor! thanks for trying it out. Do let us know here or in the openebs slack #arm channel about any question you have. There are a few more folks in the arm channel that can help.

**Comment by kmova** [comment] 2020-03-18 06:43
With release 1.8, the arm builds for NDM and Jiva have been automated. 

Pending repos are:
- cstor
- istgt
- maya
- external-storage

**Comment by radicand** [comment] 2020-03-18 12:06
Awesome news @kmova - I'm a bit confused on where to find the builds though, the tags on dockerhub appear to be CI and not version pinned (yet?). Is this just technically done, but not published out, or am I looking in the wrong place for the images?

**Comment by moritz31** [comment] 2020-04-28 06:26
Since with 1.9 there are automated builds for cstor, is there somewhere an updated yaml to test it ?

**Comment by kmova** [comment] 2020-04-28 14:37
@moritz31 -- The updated YAML is here: https://openebs.github.io/charts/openebs-operator-arm-dev.yaml

**Comment by jjbubudi** [comment] 2020-04-29 04:49
Could anyone share their experience running the images on Rpi4? What does the cpu/memory consumption look like? Is it feasible to run OpenEBS pods alongside other workloads on the same node?

**Comment by radicand** [comment] 2020-04-29 10:56
@jjbubudi , I run 1.5 currently, with plans to update to 1.9 this weekend, on a 3 now cluster consisting of a RPi4(4gb), and two RPi3(1gb). With external storage for each node, I have not found openebs to place any significant overhead; I run several deployments in this setup using a mix of Jiva (3 replications), and local storage depending on the workload. OpenEBS replication pod CPU is negligible, and memory reports range from 15mb to 25mb. The management pods are similar, 15mb to 35mb memory, CPU slightly higher (1-8m vs 1m for replication) but still negligible. Hope that helps.

**Comment by armandleopold** [comment] 2020-05-26 10:00
Hello, when taking  The updated YAML is here: https://openebs.github.io/charts/openebs-operator-arm-dev.yaml, on Raspberry Pi 4  k3s Cluster in aarch64 OS architecture, i am getting all good from the  openebs, except for the maya-apiserver 

```
pi@pi1:~ $ kubectl get all -A
NAMESPACE     NAME                                               READY   STATUS             RESTARTS   AGE
openebs       pod/openebs-snapshot-operator-546b77dc67-g54t7     2/2     Running            1          14m
openebs       pod/openebs-ndm-kckk4                              1/1     Running            0          14m
kube-system   pod/coredns-8655855d6-5qdbk                        1/1     Running            1          13h
openebs       pod/openebs-admission-server-7b897bfcdc-l5pzn      1/1     Running            0          14m
openebs       pod/openebs-ndm-nzg44                              1/1     Running            2          14m
openebs       pod/openebs-ndm-operator-76d8945d4-h4ktq           1/1     Running            4          14m
openebs       pod/openebs-provisioner-64cd65d58f-v6nwn           1/1     Running            5          14m
openebs       pod/openebs-ndm-559ww                              1/1     Running            3          14m
openebs       pod/openebs-localpv-provisioner-6f7cd99684-hq79b   1/1     Running            3          14m
openebs       pod/maya-apiserver-5d9f6f96db-l7bqb                0/1     CrashLoopBackOff   9          14m

NAMESPACE     NAME                             TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)                  AGE
default       service/kubernetes               ClusterIP   10.43.0.1      <none>        443/TCP                  13h
kube-system   service/kube-dns                 ClusterIP   10.43.0.10     <none>        53/UDP,53/TCP,9153/TCP   13h
openebs       service/maya-apiserver-service   ClusterIP   10.43.12.24    <none>        5656/TCP                 14m
openebs       service/admission-server-svc     ClusterIP   10.43.24.191   <none>        443/TCP                  9m55s

NAMESPACE   NAME                         DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
openebs     daemonset.apps/openebs-ndm   3         3         3       3            3           <none>          14m

NAMESPACE     NAME                                          READY   UP-TO-DATE   AVAILABLE   AGE
kube-system   deployment.apps/coredns                       1/1     1            1           13h
openebs       deployment.apps/openebs-admission-server      1/1     1            1           14m
openebs       deployment.apps/openebs-snapshot-operator     1/1     1            1           14m
openebs       deployment.apps/openebs-ndm-operator          1/1     1            1           14m
openebs       deployment.apps/openebs-provisioner           1/1     1            1           14m
openebs       deployment.apps/openebs-localpv-provisioner   1/1     1            1           14m
openebs       deployment.apps/maya-apiserver                0/1     1            0           14m

NAMESPACE     NAME                                                     DESIRED   CURRENT   READY   AGE
kube-system   replicaset.apps/coredns-8655855d6                        1         1         1       13h
openebs       replicaset.apps/maya-apiserver-5d9f6f96db                1         1         0       14m
openebs       replicaset.apps/openebs-admission-server-7b897bfcdc      1         1         1       14m
openebs       replicaset.apps/openebs-snapshot-operator-546b77dc67     1         1         1       14m
openebs       replicaset.apps/openebs-ndm-operator-76d8945d4           1         1         1       14m
openebs       replicaset.apps/openebs-provisioner-64cd65d58f           1         1         1       14m
openebs       replicaset.apps/openebs-localpv-provisioner-6f7cd99684   1         1         1       14m
```

I get  a :
```
pi@pi1:~ $ kubectl logs pod/maya-apiserver-5d9f6f96db-l7bqb -n openebs
standard_init_linux.go:211: exec user process caused "exec format error"
```

And description of the pod gives : 
```
pi@pi1:~ $ kubectl describe pod/maya-apiserver-5d9f6f96db-l7bqb -n openebs
Name:         maya-apiserver-5d9f6f96db-l7bqb
Namespace:    openebs
Priority:     0
Node:         pi2/192.168.2.40
Start Time:   Tue, 26 May 2020 11:41:25 +0200
Labels:       name=maya-apiserver
              openebs.io/component-name=maya-apiserver
              openebs.io/version=1.10.0
              pod-template-hash=5d9f6f96db
Annotations:  <none>
Status:       Running
IP:           10.42.1.5
IPs:
  IP:           10.42.1.5
Controlled By:  ReplicaSet/maya-apiserver-5d9f6f96db
Containers:
  maya-apiserver:
    Container ID:   containerd://c6397012b008f3439dc341091a3fa04dc3019d192bcbb6b6d333831e7518a43f
    Image:          quay.io/openebs/m-apiserver:1.10.0
    Image ID:       quay.io/openebs/m-apiserver@sha256:332bb8af16797ee017ef707b007e094dc799c02d69c1363194ccc9d7d3b8d667
    Port:           5656/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Tue, 26 May 2020 11:56:51 +0200
      Finished:     Tue, 26 May 2020 11:56:51 +0200
    Ready:          False
    Restart Count:  10
    Liveness:       exec [/usr/local/bin/mayactl version] delay=30s timeout=1s period=60s #success=1 #failure=3
    Readiness:      exec [/usr/local/bin/mayactl version] delay=30s timeout=1s period=60s #success=1 #failure=3
    Environment:
      OPENEBS_NAMESPACE:                             openebs (v1:metadata.namespace)
      OPENEBS_SERVICE_ACCOUNT:                        (v1:spec.serviceAccountName)
      OPENEBS_MAYA_POD_NAME:                         maya-apiserver-5d9f6f96db-l7bqb (v1:metadata.name)
      OPENEBS_IO_CREATE_DEFAULT_STORAGE_CONFIG:      true
      OPENEBS_IO_INSTALL_DEFAULT_CSTOR_SPARSE_POOL:  false
      OPENEBS_IO_JIVA_CONTROLLER_IMAGE:              quay.io/openebs/jiva-arm64:1.10.0
      OPENEBS_IO_JIVA_REPLICA_IMAGE:                 quay.io/openebs/jiva-arm64:1.10.0
      OPENEBS_IO_JIVA_REPLICA_COUNT:                 3
      OPENEBS_IO_CSTOR_TARGET_IMAGE:                 quay.io/openebs/cstor-istgt-arm64:1.10.0
      OPENEBS_IO_CSTOR_POOL_IMAGE:                   quay.io/openebs/cstor-pool-arm64:1.10.0
      OPENEBS_IO_CSTOR_POOL_MGMT_IMAGE:              quay.io/openebs/cstor-pool-mgmt-arm64:1.10.0
      OPENEBS_IO_CSTOR_VOLUME_MGMT_IMAGE:            quay.io/openebs/cstor-volume-mgmt-arm64:1.10.0
      OPENEBS_IO_VOLUME_MONITOR_IMAGE:               quay.io/openebs/m-exporter-arm64:1.10.0
      OPENEBS_IO_CSTOR_POOL_EXPORTER_IMAGE:          quay.io/openebs/m-exporter-arm64:1.10.0
      OPENEBS_IO_HELPER_IMAGE:                       quay.io/openebs/linux-utils-arm64:1.10.0
      OPENEBS_IO_ENABLE_ANALYTICS:                   true
      OPENEBS_IO_INSTALLER_TYPE:                     openebs-operator-arm
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from openebs-maya-operator-token-x5z9k (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  openebs-maya-operator-token-x5z9k:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  openebs-maya-operator-token-x5z9k
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                  Age                  From               Message
  ----     ------                  ----                 ----               -------
  Normal   Scheduled               <unknown>            default-scheduler  Successfully assigned openebs/maya-apiserver-5d9f6f96db-l7bqb to pi2
  Normal   Pulling                 15m                  kubelet, pi2       Pulling image "quay.io/openebs/m-apiserver:1.10.0"
  Normal   Pulled                  15m                  kubelet, pi2       Container image "quay.io/openebs/m-apiserver:1.10.0" already present on machine
  Normal   Created                 15m (x2 over 15m)    kubelet, pi2       Created container maya-apiserver
  Normal   Started                 15m (x2 over 15m)    kubelet, pi2       Started container maya-apiserver
  Warning  BackOff                 15m (x2 over 15m)    kubelet, pi2       Back-off restarting failed container
  Warning  FailedCreatePodSandBox  13m                  kubelet, pi2       Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "a4ba7f5c20f14aa6c18df53bf43fa5e47fcd0604125a48f31a9bff70392264dc": open /run/flannel/subnet.env: no such file or directory
  Normal   SandboxChanged          13m (x2 over 13m)    kubelet, pi2       Pod sandbox changed, it will be killed and re-created.
  Normal   Pulled                  9m56s (x4 over 13m)  kubelet, pi2       Container image "quay.io/openebs/m-apiserver:1.10.0" already present on machine
  Normal   Created                 9m56s (x4 over 13m)  kubelet, pi2       Created container maya-apiserver
  Normal   Started                 9m56s (x4 over 13m)  kubelet, pi2       Started container maya-apiserver
  Warning  BackOff                 80s (x48 over 11m)   kubelet, pi2       Back-off restarting failed container
pi@pi1:~ $ 
```

Can you help me ?
It seems that a sandbox pod is not able to run correctly, don't know why

**Comment by vielmetti** [comment] 2020-05-26 17:55
"exec format error" is usually a signal that the binary in a container is for the wrong architecture, which in turn is usually a signal that the container in the registry does not have multiarch support.

quay.io/openebs/m-apiserver:1.10.0

Looking at

https://github.com/openebs/maya/blob/master/buildscripts/apiserver/Makefile.mk

it appears that the arm64 binaries are in a separate container in the registry. Quay for the longest time did not have arm64 support, but now it does.

**Comment by vielmetti** [comment] 2020-05-26 17:59
the latest touch in that repo was from @kmova - are there any technical blockers to making a single multiarch image for m-apiserver  that would include both arm64 and amd64 files?

**Comment by armandleopold** [comment] 2020-05-26 19:08
Thanks  it works ! 
Editing : 
```
        image: quay.io/openebs/m-apiserver:1.10.0
```
To
```
        image: quay.io/openebs/m-apiserver-arm64:1.10.0
```

**Comment by kmova** [comment] 2020-05-27 05:49
@vielmetti @armandleopold - the multi-arch support is under development. One challenge we have currently is with managing the dependencies on the CGO / gcc for some components like NDM. The development is being tracked under: #3023 

@xUnholy is currently helping to sort this out. https://github.com/openebs/node-disk-manager/pull/428

**Comment by akhilerm** [comment] 2020-05-30 13:51
@armandleopold The fix for maya apiserver arm image is taken in [this](https://github.com/openebs/charts/pull/108) PR

**Comment by Halytskyi** [comment] 2020-06-03 03:04
I have multi-arch k8s cluster.
2 nodes amd64 and 4 nodes arm64.
In deployment I can choose only one architecture, therefore, have issue with openebs on other arch.
For example, when I use "local pv hostpath" and "openebs-localpv-provisioner" deployed on amd64, it's not working on arm64 device as "linux-utils" defined for amd64:
```
Normal  Pulled     25s   kubelet, worker02  Container image "quay.io/openebs/linux-utils@sha256:c43eda3de479248100c85b37b123bb405226185003fe7f57c1011ccb46def110" already present on machine
...
init-pvc-42ade16b-92e3-4048-9fae-cfad0ca7e317                     0/1     Error               0          3s      10.174.0.1   worker02   <none>           <none>
...
➜  ~ kubectl logs init-pvc-42ade16b-92e3-4048-9fae-cfad0ca7e317 -n openebs
standard_init_linux.go:211: exec user process caused "exec format error"
```

Any way to deploy OpenEBS on multi-arch cluster now or need wait for multi-arch containers?
Any ETA? Thanks.

**Comment by vielmetti** [comment] 2020-09-02 17:15
Bumping this issue which has gone stale, but @kmova has some earlier work on e2e pipelines for testing at https://github.com/openebs/e2e-tests/issues/405 which should be of interest.

**Comment by akhilerm** [comment] 2020-12-10 04:03
@kmova @nsathyaseelan Are there updates on the e2e pipelines for ARM.?

**Comment by nderraugh** [comment] 2020-12-30 19:03
Will this work also cover multi-arch for https://github.com/openebs/cstor-operators as well?  Currently seeing the `exec format error` messages for `openebs-cstor-csi-controller`, and `openebs-csi-node` after installing with `kubectl apply -f https://openebs.github.io/charts/cstor-operator.yaml` on an ARM64 cluster.

**Closed** 2021-04-07 00:19 UTC
Labels: armbian, no-issue-activity
