### ISSUE TITLE
couchbase stays in ContainerCreating state with openebs

### ISSUE THREAD

**Issue by dpoison** [openebs/openebs#1437] opened 2018-04-18 10:41 UTC
We have k8s 1.9.0 running cluster. 

Trying to deploy couchbase with openebs. 

Here is the status of pods. 
```
kubectl get pods
NAME                                                            READY     STATUS              RESTARTS   AGE
couchbase-0                                                     0/1       ContainerCreating   0          30m
maya-apiserver-69f9db69-vtl5b                                   1/1       Running             0          29m
openebs-provisioner-77cb47986c-pc265                            1/1       Running             0          38m
php-apache-9955bbfb5-tcv8h                                      1/1       Running             1          91d
pvc-f0e2bdf3-42eb-11e8-ae9c-b65097f6e89c-ctrl-dbbb78b97-8rs7l   2/2       Running             0          28m
pvc-f0e2bdf3-42eb-11e8-ae9c-b65097f6e89c-rep-5c8d64f596-v6mwn   1/1       Running             0          28m
pvc-f0e2bdf3-42eb-11e8-ae9c-b65097f6e89c-rep-5c8d64f596-w6wx5   1/1       Running             0          28m
pvc-f0e2bdf3-42eb-11e8-ae9c-b65097f6e89c-rep-5c8d64f596-x456l   1/1       Running             0          28m
```
openebs-operator.yaml
```
# Define the Service Account
# Define the RBAC rules for the Service Account
# Launch the maya-apiserver ( deployment )
# Launch the maya-storagemanager ( deameon set )

# Create Maya Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: openebs-maya-operator
  namespace: default
---
# Define Role that allows operations on K8s pods/deployments
#  in "default" namespace
# TODO : change to new namespace, for isolated data network
# TODO : the rules should be updated with required group/resources/verb
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: default
  name: openebs-maya-operator
rules:
- apiGroups: ["*"]
  resources: ["nodes","nodes/proxy"]
  verbs: ["get","list","watch","create","update"]
- apiGroups: ["*"]
  resources: ["namespaces","services","pods","deployments", "events", "endpoints"]
  verbs: ["*"]
- apiGroups: ["*"]
  resources: ["persistentvolumes","persistentvolumeclaims"]
  verbs: ["*"]
- apiGroups: ["storage.k8s.io"]
  resources: ["storageclasses"]
  verbs: ["*"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: [ "get", "list", "create" ]
- apiGroups: ["*"]
  resources: ["storagepools"]
  verbs: ["get", "list"] 
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
---
# Bind the Service Account with the Role Privileges.
# TODO: Check if default account also needs to be there
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: openebs-maya-operator
  namespace: default
subjects:
- kind: ServiceAccount
  name: openebs-maya-operator
  namespace: default
- kind: User
  name: system:serviceaccount:default:default
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: openebs-maya-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: maya-apiserver
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: maya-apiserver
    spec:
      serviceAccountName: openebs-maya-operator
      containers:
      - name: maya-apiserver
        imagePullPolicy: Always
        image: openebs/m-apiserver:0.5.3
        ports:
        - containerPort: 5656
        env:
        # OPENEBS_IO_KUBE_CONFIG enables maya api service to connect to K8s
        # based on this config. This is ignored if empty.
        # This is supported for maya api server version 0.5.2 onwards
        - name: OPENEBS_IO_KUBE_CONFIG
          value: "/etc/kubernetes/kubeconfig"
        # OPENEBS_IO_K8S_MASTER enables maya api service to connect to K8s
        # based on this address. This is ignored if empty.
        # This is supported for maya api server version 0.5.2 onwards
        - name: OPENEBS_IO_K8S_MASTER
          value: "http://192.168.51.77:443"
        - name: OPENEBS_IO_JIVA_CONTROLLER_IMAGE
          value: "openebs/jiva:0.5.3"
        - name: OPENEBS_IO_JIVA_REPLICA_IMAGE
          value: "openebs/jiva:0.5.3"
        - name: OPENEBS_IO_VOLUME_MONITOR_IMAGE
          value: "openebs/m-exporter:0.5.3"
        - name: OPENEBS_IO_JIVA_REPLICA_COUNT
          value: "3"
---
apiVersion: v1
kind: Service
metadata:
  name: maya-apiserver-service
spec:
  ports:
  - name: api
    port: 5656
    protocol: TCP
    targetPort: 5656
  selector:
    name: maya-apiserver
  sessionAffinity: None
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: openebs-provisioner
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: openebs-provisioner
    spec:
      serviceAccountName: openebs-maya-operator
      containers:
      - name: openebs-provisioner
        imagePullPolicy: Always
        image: openebs/openebs-k8s-provisioner:0.5.3
        env:
        # OPENEBS_IO_K8S_MASTER enables openebs provisioner to connect to K8s
        # based on this address. This is ignored if empty.
        # This is supported for openebs provisioner version 0.5.2 onwards
        # - name: OPENEBS_IO_K8S_MASTER
        #  value: "http://192.168.51.77:443"
        # OPENEBS_IO_KUBE_CONFIG enables openebs provisioner to connect to K8s
        # based on this config. This is ignored if empty.
        # This is supported for openebs provisioner version 0.5.2 onwards
        # - name: OPENEBS_IO_KUBE_CONFIG
        #  value: "/etc/kubernetes/kubeconfig"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: OPENEBS_MONITOR_URL
          value: "http://127.0.0.1:32515/dashboard/db/openebs-volume-stats?orgId=1"
        - name: OPENEBS_MONITOR_VOLKEY
          value: "&var-OpenEBS"
        - name: MAYA_PORTAL_URL
          value: "https://mayaonline.io/"
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: storagepoolclaims.openebs.io
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: openebs.io
  # version name to use for REST API: /apis/<group>/<version>
  version: v1alpha1
  # either Namespaced or Cluster
  scope: Cluster
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: storagepoolclaims
    # singular name to be used as an alias on the CLI and for display
    singular: storagepoolclaim
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: StoragePoolClaim
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - spc
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: storagepools.openebs.io
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: openebs.io
  # version name to use for REST API: /apis/<group>/<version>
  version: v1alpha1
  # either Namespaced or Cluster
  scope: Cluster
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: storagepools
    # singular name to be used as an alias on the CLI and for display
    singular: storagepool
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: StoragePool
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - sp
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: openebs-standard
provisioner: openebs.io/provisioner-iscsi
parameters:
  openebs.io/storage-pool: "default"
  openebs.io/jiva-replica-count: "2"
  openebs.io/volume-monitor: "true"
  openebs.io/capacity: 5G
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: volumepolicies.openebs.io
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: openebs.io
  # version name to use for REST API: /apis/<group>/<version>
  version: v1alpha1
  # either Namespaced or Cluster
  scope: Cluster
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: volumepolicies
    # singular name to be used as an alias on the CLI and for display
    singular: volumepolicy
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: VolumePolicy
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - vp
```
openebs-config.yaml

```
apiVersion: openebs.io/v1alpha1
kind: StoragePool
metadata:
  name: default
  type: hostdir
spec:
  path: "/var/openebs" 
  nodes: [ "all" ]
  #maxVolSize: 10G #Max Volume Size
  #maxAllocatedSize: 100G #Max Total Space allocated from this directory/mount
---
```
openebs-storageclasses.yaml
```
# Define a storage classes supported by OpenEBS
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: openebs-standalone
provisioner: openebs.io/provisioner-iscsi
parameters:
  openebs.io/storage-pool: "default"
  openebs.io/jiva-replica-count: "1"
  openebs.io/volume-monitor: "true"
  openebs.io/capacity: 5G
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: openebs-percona
provisioner: openebs.io/provisioner-iscsi
parameters:
  openebs.io/storage-pool: "default"
  openebs.io/jiva-replica-count: "1"
  openebs.io/volume-monitor: "true"
  openebs.io/capacity: 5G
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: openebs-jupyter
provisioner: openebs.io/provisioner-iscsi
parameters:
  openebs.io/storage-pool: "default"
  openebs.io/jiva-replica-count: "2"
  openebs.io/volume-monitor: "true"
  openebs.io/capacity: 5G
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: openebs-mongodb
provisioner: openebs.io/provisioner-iscsi
parameters:
  openebs.io/storage-pool: "default"
  openebs.io/jiva-replica-count: "2"
  openebs.io/volume-monitor: "true"
  openebs.io/capacity: 5G
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: openebs-cassandra
provisioner: openebs.io/provisioner-iscsi
parameters:
  openebs.io/storage-pool: "default"
  openebs.io/jiva-replica-count: "2"
  openebs.io/volume-monitor: "true"
  openebs.io/capacity: 5G
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: openebs-redis
provisioner: openebs.io/provisioner-iscsi
parameters:
  openebs.io/storage-pool: "default"
  openebs.io/jiva-replica-count: "2"
  openebs.io/volume-monitor: "true"
  openebs.io/capacity: 5G
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: openebs-kafka
provisioner: openebs.io/provisioner-iscsi
parameters:
  openebs.io/storage-pool: "default"
  openebs.io/jiva-replica-count: "2"
  openebs.io/volume-monitor: "true"
  openebs.io/capacity: 10G
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: openebs-zk
provisioner: openebs.io/provisioner-iscsi
parameters:
  openebs.io/storage-pool: "default"
  openebs.io/jiva-replica-count: "2"
  openebs.io/volume-monitor: "true"
  openebs.io/capacity: 5G
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: openebs-es-data-sc
provisioner: openebs.io/provisioner-iscsi
parameters:
  openebs.io/storage-pool: "default"
  openebs.io/jiva-replica-count: "2"
  openebs.io/volume-monitor: "true"
  openebs.io/capacity: 5G
---
```
couchbase-statefulset.yaml
```
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: couchbase
spec:
  serviceName: "couchbase"
  replicas: 1
  template:
    metadata:
      labels:
        app: couchbase
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: couchbase
        image: saturnism/couchbase:k8s-petset
        ports:
        - containerPort: 8091
        volumeMounts:
        - name: couchbase-data
          mountPath: /opt/couchbase/var
        env:
          - name: COUCHBASE_MASTER
            value: "couchbase-0.couchbase.default.svc.cluster.local"
          - name: AUTO_REBALANCE
            value: "false"
  volumeClaimTemplates:
  - metadata:
      name: couchbase-data
      annotations:
        volume.beta.kubernetes.io/storage-class: openebs-standard
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5G
```
couchbase-service.yaml
```
apiVersion: v1
kind: Service
metadata:
  name: couchbase
  labels:
    app: couchbase
spec:
  ports:
  - port: 8091
    name: couchbase
  # *.couchbase.default.svc.cluster.local
  clusterIP: None
  selector:
    app: couchbase
---
apiVersion: v1
kind: Service
metadata:
  name: couchbase-ui
  labels:
    app: couchbase-ui
spec:
  ports:
  - port: 8091
    name: couchbase
  selector:
    app: couchbase
  sessionAffinity: ClientIP
  type: NodePort
```
While **kubectl get svc** out put is 
```
NAME                                                TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)             AGE
couchbase                                           ClusterIP   None         <none>        8091/TCP            41m
couchbase-ui                                        NodePort    10.3.0.115   <none>        8091:30966/TCP      41m
kubernetes                                          ClusterIP   10.3.0.1     <none>        443/TCP             103d
maya-apiserver-service                              ClusterIP   10.3.0.248   <none>        5656/TCP            1h
php-apache                                          ClusterIP   10.3.0.235   <none>        80/TCP              91d
pvc-f0e2bdf3-42eb-11e8-ae9c-b65097f6e89c-ctrl-svc   ClusterIP   10.3.0.124   <none>        3260/TCP,9501/TCP   58m
```
**kubectl get sc**
```
NAME                     PROVISIONER                    AGE
openebs-cassandra        openebs.io/provisioner-iscsi   1h
openebs-es-data-sc       openebs.io/provisioner-iscsi   1h
openebs-jupyter          openebs.io/provisioner-iscsi   1h
openebs-kafka            openebs.io/provisioner-iscsi   1h
openebs-mongodb          openebs.io/provisioner-iscsi   1h
openebs-percona          openebs.io/provisioner-iscsi   1h
openebs-redis            openebs.io/provisioner-iscsi   1h
openebs-standalone       openebs.io/provisioner-iscsi   1h
openebs-standard         openebs.io/provisioner-iscsi   1h
openebs-standard-0.6.0   openebs.io/provisioner-iscsi   1m
openebs-zk               openebs.io/provisioner-iscsi   1h
```
**kubectl get pv**
```
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS    CLAIM                                STORAGECLASS       REASON    AGE
pvc-f0e2bdf3-42eb-11e8-ae9c-b65097f6e89c   5G         RWO            Delete           Bound     default/couchbase-data-couchbase-0   openebs-standard             59m
```
**kubectl get pvc**
```
NAME                         STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS       AGE
couchbase-data-couchbase-0   Bound     pvc-f0e2bdf3-42eb-11e8-ae9c-b65097f6e89c   5G         RWO            openebs-standard   1h
```
**kubectl describe pod couchbase-0**
```
Name:           couchbase-0
Namespace:      default
Node:           kvmw3.example.com/192.168.53.79
Start Time:     Wed, 18 Apr 2018 11:53:49 +0200
Labels:         app=couchbase
                controller-revision-hash=couchbase-6698fcc56
Annotations:    kubernetes.io/created-by={"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"StatefulSet","namespace":"default","name":"couchbase","uid":"64aea41f-42ee-11e8-ae9c-b65097f6e89c","apiVer...
Status:         Pending
IP:
Controlled By:  StatefulSet/couchbase
Containers:
  couchbase:
    Container ID:
    Image:          saturnism/couchbase:k8s-petset
    Image ID:
    Port:           8091/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:
      COUCHBASE_MASTER:  couchbase-0.couchbase.default.svc.cluster.local
      AUTO_REBALANCE:    false
    Mounts:
      /opt/couchbase/var from couchbase-data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-7gbf9 (ro)
Conditions:
  Type           Status
  Initialized    True
  Ready          False
  PodScheduled   True
Volumes:
  couchbase-data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  couchbase-data-couchbase-0
    ReadOnly:   false
  default-token-7gbf9:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-7gbf9
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     <none>
Events:
  Type     Reason                 Age                 From                        Message
  ----     ------                 ----                ----                        -------
  Normal   Scheduled              43m                 default-scheduler           Successfully assigned couchbase-0 to kvmw3.example.com
  Normal   SuccessfulMountVolume  43m                 kubelet, kvmw3.example.com  MountVolume.SetUp succeeded for volume "default-token-7gbf9"
  Warning  FailedMount            46s (x19 over 41m)  kubelet, kvmw3.example.com  Unable to mount volumes for pod "couchbase-0_default(64dcbe15-42ee-11e8-ae9c-b65097f6e89c)": timeout expired waiting for volumes to attach/mount for pod "default"/"couchbase-0". list of unattached/unmounted volumes=[couchbase-data]

```
couchbase-0 stays in *ContainerCreating* state only. Can anyone help on this?

Thanks in advance.

**Comment by ksatchit** [comment] 2018-04-18 11:51
Is the iSCSI initiator packages available on the nodes ?

**Comment by dpoison** [comment] 2018-04-18 12:04
Yes @ksatchit   , iSCSI initiator package is available and in running state.

**Comment by ksatchit** [comment] 2018-04-19 13:50
@dpoison , how has the Kubernetes cluster been setup, is the kubelet running in a container ? Also, can you try using the logger here to collect the pod & system logs ? (https://github.com/openebs/litmus/tree/master/logger)

**Comment by ronakpandya7** [comment] 2018-04-20 13:51
Hello @ksatchit,
Thanks for the reply.

When we execute couchbase-0 describe :

```
Events:
  Type     Reason                  Age               From                        Message
  ----     ------                  ----              ----                        -------
  Warning  FailedScheduling        3m (x7 over 3m)   default-scheduler           pod has unbound PersistentVolumeClaims (repeated 2 times)
  Normal   Scheduled               2m                default-scheduler           Successfully assigned couchbase-0 to node2.example.com
  Normal   SuccessfulAttachVolume  2m                attachdetach-controller     AttachVolume.Attach succeeded for volume "pvc-b8b8f133-449f-11e8-9e0e-9c8e992d4ab8"
  Normal   SuccessfulMountVolume   2m                kubelet, node2.example.com  MountVolume.SetUp succeeded for volume "default-token-kp5b6"
  Warning  FailedMount             34s               kubelet, node2.example.com  Unable to mount volumes for pod "couchbase-0_default(b8ba66e5-449f-11e8-9e0e-9c8e992d4ab8)": timeout expired waiting
 for volumes to attach or mount for pod "default"/"couchbase-0". list of unmounted volumes=[couchbase-data]. list of unattached volumes=[couchbase-data default-token-kp5b6]
  Warning  FailedMount             27s (x9 over 2m)  kubelet, node2.example.com  MountVolume.WaitForAttach failed for volume "pvc-b8b8f133-449f-11e8-9e0e-9c8e992d4ab8" : executable file not found i
n $PATH
```

maya apiserver  logs

```
I0420 13:35:48.174120       7 start.go:122] Initializing maya-apiserver...
I0420 13:35:48.174272       7 start.go:231] Starting maya api server ...
I0420 13:35:48.174287       7 registry.go:50] Registered 'kubernetes' as orchestration provider
I0420 13:35:48.174304       7 registry.go:50] Registered 'nomad' as orchestration provider
I0420 13:35:48.174427       7 start.go:160] Maya api server configuration:
I0420 13:35:48.174444       7 start.go:162]          Log Level: INFO
I0420 13:35:48.174455       7 start.go:162]             Region: global (DC: dc1)
I0420 13:35:48.174463       7 start.go:162]            Version: v0.5.1-pre-release
I0420 13:35:48.174468       7 start.go:168]
I0420 13:35:48.174474       7 start.go:171] Maya api server started! Log data will stream in below:
2018/04/20 13:36:31.299765 [DEBUG] http: Request /latest/volumes/ (POST)
[DEBUG] Processing POST request
I0420 13:36:31.299801       7 volume_endpoint.go:263] Processing Volume add request
I0420 13:36:31.337269       7 util.go:1205] Will use env var 'DEFAULT_PVP_NAME: '
I0420 13:36:31.337293       7 jiva.go:56] Building new instance of jiva persistent volume provisioner 'volumeprovisioner.mapi.openebs.io/name:jiva'
I0420 13:36:31.337304       7 util.go:1205] Will use env var 'DEFAULT_ORCHESTRATOR_NAME: '
I0420 13:36:31.337312       7 k8s.go:59] Building 'orchprovider.mapi.openebs.io/name':'kubernetes' orchestration provider
I0420 13:36:31.337329       7 util.go:1205] Will use env var 'DEFAULT_ORCHESTRATOR_IN_CLUSTER: '
I0420 13:36:31.339882       7 k8s.go:1211] Adding service for Volume 'name : pvc-b8b8f133-449f-11e8-9e0e-9c8e992d4ab8'
I0420 13:36:31.367735       7 k8s.go:1251] Added service 'name: pvc-b8b8f133-449f-11e8-9e0e-9c8e992d4ab8-ctrl-svc'
I0420 13:36:31.367771       7 util.go:1205] Will use env var 'DEFAULT_ORCHESTRATOR_IN_CLUSTER: '
I0420 13:36:31.408254       7 util.go:1205] Will use env var 'DEFAULT_ORCHESTRATOR_IN_CLUSTER: '
I0420 13:36:31.410887       7 k8s.go:861] Adding controller for VSM 'name: pvc-b8b8f133-449f-11e8-9e0e-9c8e992d4ab8'
I0420 13:36:31.410917       7 util.go:1205] Will use env var 'DEFAULT_CONTROLLER_NODE_TAINT_TOLERATION: '
I0420 13:36:31.498308       7 k8s.go:972] Added controller 'name: pvc-b8b8f133-449f-11e8-9e0e-9c8e992d4ab8-ctrl'
I0420 13:36:31.498350       7 util.go:1205] Will use env var 'DEFAULT_ORCHESTRATOR_IN_CLUSTER: '
I0420 13:36:31.502637       7 k8s.go:1031] Adding replica(s) for VSM 'pvc-b8b8f133-449f-11e8-9e0e-9c8e992d4ab8'
I0420 13:36:31.502661       7 util.go:1205] Will use env var 'DEFAULT_REPLICA_TOPOLOGY_KEY: '
I0420 13:36:31.502683       7 util.go:1205] Will use env var 'DEFAULT_REPLICA_NODE_TAINT_TOLERATION: '
I0420 13:36:31.553688       7 k8s.go:1179] Successfully added replica(s) 'count: 842354783048' for VSM 'pvc-b8b8f133-449f-11e8-9e0e-9c8e992d4ab8-rep'
I0420 13:36:31.553716       7 volume_endpoint.go:312] Processed Volume add request successfully for 'pvc-b8b8f133-449f-11e8-9e0e-9c8e992d4ab8'
2018/04/20 13:36:31.553976 [DEBUG] http: Request /latest/volumes/ (254.21321ms)
2018/04/20 13:36:31.554592 [DEBUG] http: Request /latest/volumes/info/pvc-b8b8f133-449f-11e8-9e0e-9c8e992d4ab8 (GET)
[DEBUG] Processing GET request
I0420 13:36:31.554629       7 volume_endpoint.go:132] Processing Volume read request
I0420 13:36:31.554661       7 util.go:1205] Will use env var 'DEFAULT_PVP_NAME: '
I0420 13:36:31.554675       7 jiva.go:56] Building new instance of jiva persistent volume provisioner 'volumeprovisioner.mapi.openebs.io/name:jiva'
I0420 13:36:31.554688       7 util.go:1205] Will use env var 'DEFAULT_ORCHESTRATOR_NAME: '
I0420 13:36:31.554698       7 k8s.go:59] Building 'orchprovider.mapi.openebs.io/name':'kubernetes' orchestration provider
I0420 13:36:31.554719       7 util.go:1205] Will use env var 'DEFAULT_ORCHESTRATOR_IN_CLUSTER: '
I0420 13:36:31.557621       7 util.go:1205] Will use env var 'DEFAULT_ORCHESTRATOR_IN_CLUSTER: '
I0420 13:36:31.560090       7 util.go:1205] Will use env var 'DEFAULT_ORCHESTRATOR_IN_CLUSTER: '
I0420 13:36:31.562702       7 k8s.go:521] Fetching info on volume 'default: pvc-b8b8f133-449f-11e8-9e0e-9c8e992d4ab8'
I0420 13:36:31.994674       7 k8s.go:626] Info fetched successfully for volume 'default: pvc-b8b8f133-449f-11e8-9e0e-9c8e992d4ab8'
I0420 13:36:31.994698       7 volume_endpoint.go:188] Processed Volume read request successfully for 'pvc-b8b8f133-449f-11e8-9e0e-9c8e992d4ab8'
2018/04/20 13:36:31.994832 [DEBUG] http: Request /latest/volumes/info/pvc-b8b8f133-449f-11e8-9e0e-9c8e992d4ab8 (440.2408ms)
```

openebs-provisioner logs

```
I0420 13:35:46.213091       1 maya_api.go:63] OpenEBS volume provisioner namespace default
I0420 13:35:46.220433       1 controller.go:407] Starting provisioner controller baf93a2b-449f-11e8-ba53-a6e4e1200603!
I0420 13:35:46.228406       1 controller.go:1080] scheduleOperation[lock-provision-default/couchbase-data-couchbase-0[b8b8f133-449f-11e8-9e0e-9c8e992d4ab8]]
I0420 13:35:46.283667       1 leaderelection.go:156] attempting to acquire leader lease...
I0420 13:35:46.362464       1 leaderelection.go:178] successfully acquired lease to provision for pvc default/couchbase-data-couchbase-0
I0420 13:35:46.362569       1 controller.go:1080] scheduleOperation[provision-default/couchbase-data-couchbase-0[b8b8f133-449f-11e8-9e0e-9c8e992d4ab8]]
I0420 13:35:46.372592       1 controller.go:1080] scheduleOperation[provision-default/couchbase-data-couchbase-0[b8b8f133-449f-11e8-9e0e-9c8e992d4ab8]]
I0420 13:36:01.228719       1 controller.go:1080] scheduleOperation[provision-default/couchbase-data-couchbase-0[b8b8f133-449f-11e8-9e0e-9c8e992d4ab8]]
I0420 13:36:16.229080       1 controller.go:1080] scheduleOperation[provision-default/couchbase-data-couchbase-0[b8b8f133-449f-11e8-9e0e-9c8e992d4ab8]]
E0420 13:36:16.388840       1 maya_api.go:110] Error when connecting maya-apiserver Post http://10.3.0.119:5656/latest/volumes/: dial tcp 10.3.0.119:5656: i/o timeout
E0420 13:36:16.388884       1 openebs-provisioner.go:109] Error creating volume: Post http://10.3.0.119:5656/latest/volumes/: dial tcp 10.3.0.119:5656: i/o timeout
E0420 13:36:16.388924       1 controller.go:808] Failed to provision volume for claim "default/couchbase-data-couchbase-0" with StorageClass "openebs-standard": Post http://10.3.0.119:5656/latest/volumes/: dial tcp 10.3.0.119:5656: i/o timeout
E0420 13:36:16.389097       1 goroutinemap.go:166] Operation for "provision-default/couchbase-data-couchbase-0[b8b8f133-449f-11e8-9e0e-9c8e992d4ab8]" failed. No retries permitted until 2018-04-20 13:36:16.889055539 +0000 UTC (durationBeforeRetry 500ms). Error: Post http://10.3.0.119:5656/latest/volumes/: dial tcp 10.3.0.119:5656: i/o timeout
I0420 13:36:16.633140       1 leaderelection.go:198] stopped trying to renew lease to provision for pvc default/couchbase-data-couchbase-0, task failed
I0420 13:36:31.229238       1 controller.go:1080] scheduleOperation[provision-default/couchbase-data-couchbase-0[b8b8f133-449f-11e8-9e0e-9c8e992d4ab8]]
I0420 13:36:31.554221       1 maya_api.go:127] volume Successfully Created:
{"metadata":{"creationTimestamp":null,"labels":{},"name":"pvc-b8b8f133-449f-11e8-9e0e-9c8e992d4ab8"},"status":{"Message":"","Phase":"","Reason":""}}
I0420 13:36:31.995253       1 controller.go:813] volume "pvc-b8b8f133-449f-11e8-9e0e-9c8e992d4ab8" for claim "default/couchbase-data-couchbase-0" created
I0420 13:36:32.096565       1 controller.go:830] volume "pvc-b8b8f133-449f-11e8-9e0e-9c8e992d4ab8" for claim "default/couchbase-data-couchbase-0" saved
I0420 13:36:32.096588       1 controller.go:866] volume "pvc-b8b8f133-449f-11e8-9e0e-9c8e992d4ab8" provisioned for claim "default/couchbase-data-couchbase-0"

Can you please check this?
```

**Comment by ksatchit** [comment] 2018-04-20 14:35
The maya-apiserver & provisioner logs look OK. Which is why the PV is created successfully.  Typically, this points to an inability to find the iSCSI initiator (is the iscsiadm available in $PATH ?) 

`MountVolume.WaitForAttach failed for volume "pvc-b8b8f133-449f-11e8-9e0e-9c8e992d4ab8" : executable file not found in $PATH`

**Comment by ronakpandya7** [comment] 2018-04-20 14:52
But which path you are talking about for iSCSI initiator?
What is $PATH indicates for?

**Comment by jaykhengar** [comment] 2018-04-20 17:01
Thanks for the explaination @ksatchit 
Out K8s is running on CoreOS

echo $PATH output:
```
node1 ~ # echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/opt/bin
```

which iscsiadm output:

```
node1 ~ # which iscsiadm
/usr/sbin/iscsiadm
```

I have executed this commands on our hosts.
What should be ideal place of it? On host or in container? Actually we are not sure about it.
Please check the outputs.

**Comment by ronakpandya7** [comment] 2018-04-24 08:00
Hello All,

The issue is solved now :)

Thanks for the support

**Comment by ksatchit** [comment] 2018-04-24 11:51
Great, thanks for the update @ronakpandya7 ! 

The steps for coreos has to go into this doc : https://docs.openebs.io/docs/next/prerequisites.html#steps-for-configuring-and-verifying-open-iscsi

@mahebbar

**Comment by ksatchit** [comment] 2018-06-28 08:44
Closing this issue based on the updates by @ronakpandya7

**Closed by ksatchit** 2018-06-28 08:44 UTC
Labels: documentation
