### ISSUE TITLE
cstor invalid bearer token, Token has been invalidated

### ISSUE THREAD

**Issue by runningman84** [openebs/openebs#2325] opened 2018-12-13 17:55 UTC
I get a lot of error message from the kube api server caused by the cstor-spare-pool pods:

```
openebs/cstor-sparse-pool-ll2s-7c5c46f997-wnzn6[cstor-pool-mgmt]: E1213 17:44:24.396117       8 reflector.go:205] github.com/openebs/maya/pkg/client/generated/informer/externalversions/factory.go:117: Failed to list *v1alpha1.CStorPool: Unauthorized
kube-system/kube-apiserver-lepotato[kube-apiserver]: E1213 17:44:24.930704       1 authentication.go:65] Unable to authenticate the request due to an error: [invalid bearer token, [invalid bearer token, Token has been invalidated]]
openebs/cstor-sparse-pool-dju2-588689bf7b-fsvbf[cstor-pool-mgmt]: E1213 17:44:24.935454       8 reflector.go:205] github.com/openebs/maya/pkg/client/generated/informer/externalversions/factory.go:117: Failed to list *v1alpha1.CStorVolumeReplica: Unauthorized
kube-system/kube-apiserver-lepotato[kube-apiserver]: E1213 17:44:24.967494       1 authentication.go:65] Unable to authenticate the request due to an error: [invalid bearer token, [invalid bearer token, Token has been invalidated]]
openebs/cstor-sparse-pool-ll2s-7c5c46f997-wnzn6[cstor-pool-mgmt]: E1213 17:44:24.975339       8 reflector.go:205] github.com/openebs/maya/pkg/client/generated/informer/externalversions/factory.go:117: Failed to list *v1alpha1.CStorVolumeReplica: Unauthorized
```

Maybe the current helm chart does not create the correct rbac rules or this is some general bug?

## Steps to Reproduce
```
helm install --namespace openebs --name openebs stable/openebs
```

## Your Environment

```sh 
* `kubectl get nodes`:
~ >>> kubectl get nodes                                                                                                                                       
NAME       STATUS   ROLES    AGE   VERSION
cubi001    Ready    <none>   12d   v1.13.0
cubi002    Ready    <none>   12d   v1.13.0
lepotato   Ready    master   12d   v1.13.0

* `kubectl get pods --all-namespaces`:
~ >>> kubectl get pods --all-namespaces                                                                                                                       
NAMESPACE        NAME                                                              READY   STATUS      RESTARTS   AGE
ingress          nginx-ingress-controller-6b8d85dbdc-jtwvx                         1/1     Running     1          8d
ingress          nginx-ingress-default-backend-7b98d4dc6c-8x2z8                    1/1     Running     7          11d
kube-system      coredns-86c58d9df4-mv8m9                                          1/1     Running     3          7d22h
kube-system      coredns-86c58d9df4-qg486                                          1/1     Running     2          7d22h
kube-system      etcd-lepotato                                                     1/1     Running     2          7d22h
kube-system      kube-apiserver-lepotato                                           1/1     Running     2          7d22h
kube-system      kube-controller-manager-lepotato                                  1/1     Running     2          7d22h
kube-system      kube-router-cpf27                                                 1/1     Running     9          12d
kube-system      kube-router-pnqnr                                                 1/1     Running     9          12d
kube-system      kube-router-q9xzc                                                 1/1     Running     6          11d
kube-system      kube-scheduler-lepotato                                           1/1     Running     2          7d22h
kube-system      tiller-deploy-6f6fd74b68-hts9n                                    1/1     Running     5          11d
logging          elasticsearch-0                                                   1/1     Running     0          49m
logging          fluent-bit-2j9qx                                                  1/1     Running     3          7d22h
logging          fluent-bit-b4wck                                                  1/1     Running     1          7d22h
logging          kibana-7c5c85c484-xgcck                                           1/1     Running     1          7d21h
logging          pvc-c0cdc122-fef8-11e8-b312-b2318eace40e-ctrl-7d77659b59-6q2fg    2/2     Running     0          49m
logging          pvc-c0cdc122-fef8-11e8-b312-b2318eace40e-rep-54c8d84689-mnfxr     1/1     Running     0          49m
logging          sjr-pvc-f5d3e273-fef3-11e8-b312-b2318eace40e-5lap-d6g2m           0/1     Completed   0          49m
logging          sjr-pvc-f5d3e273-fef3-11e8-b312-b2318eace40e-qz2q-fhzc4           0/1     Completed   0          49m
metallb-system   metallb-controller-5d646d4c-7f4lh                                 1/1     Running     6          10d
metallb-system   metallb-speaker-4snln                                             1/1     Running     6          10d
metallb-system   metallb-speaker-mk57f                                             1/1     Running     4          10d
monitoring       alertmanager-prometheus-operator-alertmanager-0                   2/2     Running     6          9d
monitoring       metrics-server-84484ccd9-hlx9s                                    1/1     Running     11         7d21h
monitoring       prometheus-operator-grafana-96bdbd579-ffnm6                       3/3     Running     96         9d
monitoring       prometheus-operator-kube-state-metrics-6b79d57dc-v6698            1/1     Running     18         9d
monitoring       prometheus-operator-operator-5969b58864-ls9qf                     1/1     Running     18         9d
monitoring       prometheus-operator-prometheus-node-exporter-6jmtw                1/1     Running     3          9d
monitoring       prometheus-operator-prometheus-node-exporter-k7xgk                1/1     Running     7          9d
monitoring       prometheus-operator-prometheus-node-exporter-s7pqp                1/1     Running     5          9d
monitoring       prometheus-prometheus-operator-prometheus-0                       3/3     Running     10         8d
openebs          cstor-sparse-pool-dju2-588689bf7b-fsvbf                           2/2     Running     0          3d20h
openebs          cstor-sparse-pool-ll2s-7c5c46f997-wnzn6                           2/2     Running     0          3d20h
openebs          openebs-apiserver-7b799f5cd9-2ccgq                                1/1     Running     0          3h41m
openebs          openebs-ndm-7rfzb                                                 1/1     Running     0          3h41m
openebs          openebs-ndm-h6stk                                                 1/1     Running     0          3h41m
openebs          openebs-provisioner-6848b9f986-75ctm                              1/1     Running     0          3h41m
openebs          openebs-snapshot-operator-68c65b8767-kjdxp                        2/2     Running     0          3h41m
openebs          pvc-014913c7-fbe5-11e8-9d65-dec450c7748d-target-689b545dfbqqrfc   3/3     Running     1          48m
openebs          pvc-ecdf1db9-fbf0-11e8-9d65-dec450c7748d-target-bfcdc9565-j2dbh   3/3     Running     1          3h38m
pihole           pihole-88866f84-c582q                                             2/2     Running     0          3d23h

* `kubectl get services`:

* `kubectl get sc`:
~ >>> kubectl get sc                                                                                                                                          
NAME                        PROVISIONER                                                AGE
openebs-cstor-raid1         openebs.io/provisioner-iscsi                               3d22h
openebs-cstor-single        openebs.io/provisioner-iscsi                               3d22h
openebs-cstor-sparse        openebs.io/provisioner-iscsi                               7d21h
openebs-jiva-default        openebs.io/provisioner-iscsi                               7d21h
openebs-jiva-raid1          openebs.io/provisioner-iscsi                               3d22h
openebs-jiva-single         openebs.io/provisioner-iscsi                               3d22h
openebs-snapshot-promoter   volumesnapshot.external-storage.k8s.io/snapshot-promoter   7d21h

* `kubectl get pv`:
~ >>> kubectl get pvc                                                                                                                                         
NAME                   STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS          AGE
data-elasticsearch-0   Bound    pvc-c0cdc122-fef8-11e8-b312-b2318eace40e   5G         RWO            openebs-jiva-single   49m

* `kubectl get pvc`:
~ >>> kubectl get pv                                                                                                                                          
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                          STORAGECLASS          REASON   AGE
pvc-c0cdc122-fef8-11e8-b312-b2318eace40e   5G         RWO            Delete           Bound    logging/data-elasticsearch-0   openebs-jiva-single            50m
```

* OS (from `/etc/os-release`):
phil@cubi001:~$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
* Kernel (from `uname -a`):
phil@cubi001:~$ uname -a
Linux cubi001 4.15.0-42-generic #45-Ubuntu SMP Thu Nov 15 19:32:57 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* Install tools:
kubeadm
* Others:

**Comment by runningman84** [comment] 2018-12-17 20:05
@prateekpandey14 @kmova do you need any additional info?

**Comment by kmova** [comment] 2019-02-21 17:21
@runningman84 - Apologize for the delay in responding and thank you for resurfacing it today with @epowell101!

cstor-sparse (pool-mgmt) pod needs to access the custom resources. The configuration / RBAC seems be appropriate since maya-apiserver uses the same service account and is able to interact with the K8s to provision the pools and volumes. 

Couple of questions: 
(a) Was the K8s upgraded after installing OpenEBS?
(b) Did you already try to run the steps mentioned https://github.com/kubernetes/kubernetes/issues/22351#issuecomment-230029843 to - revalidate the tokens?

**Comment by runningman84** [comment] 2019-02-21 17:48
The k8s version was not updated back then. Just the openebs helm chart was updated. But uninstalling and reinstalling the chart did not help either.
I was not aware how to update the tokens. If this is a common problem you might want to add this to your faq.

**Comment by kmova** [comment] 2019-02-21 18:04
@runningman84 - one more question. what do you mean by update - openebs helm chart? were you running 0.7.x and updated to 0.8.0?

**Comment by runningman84** [comment] 2019-02-22 06:49
Yes I updated the helm chart which also contains the 0.8 openebs image

**Comment by kmova** [comment] 2019-02-22 16:19
Thanks @runningman84. I will try those steps and check I can reproduce it.

**Comment by kmova** [comment] 2019-02-26 06:18
@runningman84  I have setup with pools and volumes created. And followed the helm upgrade step. 
```
kiran_mova@kmova-dev:~$ helm history ut
REVISION        UPDATED                         STATUS          CHART           DESCRIPTION     
1               Sun Feb 24 06:45:30 2019        SUPERSEDED      openebs-0.8.2   Install complete
2               Tue Feb 26 06:12:16 2019        DEPLOYED        openebs-0.8.2   Upgrade complete
kiran_mova@kmova-dev:~$ 
```

I see that the `cstor-pool-mgmt` is able to access and update the required CRs:

```
I0226 06:16:32.413470       6 handler.go:143] Synchronizing CstorVolumeReplica status for volume pvc-ee4f0669-3927-11e9-a917-42010a800089-cstor-sparse-pool-mo1r
I0226 06:16:32.436955       6 handler.go:94] cVR:pvc-ee4f0669-3927-11e9-a917-42010a800089-cstor-sparse-pool-mo1r, ee7f133b-3927-11e9-a917-42010a800089; Status: Healthy
I0226 06:16:32.437077       6 run_replica_controller.go:109] Successfully synced 'openebs/pvc-ee4f0669-3927-11e9-a917-42010a800089-cstor-sparse-pool-mo1r' for operation: Sync
```

Would it possible for you to reproduce the issue again @runningman84?

**Comment by chandankumar4** [comment] 2019-02-26 09:37
I'm trying to reproduce this issue but didn't see any issue related to **cstor-spare-pool** in kube-apiserver log
```
$ helm history openebs
REVISION	UPDATED                 	STATUS    	CHART        	DESCRIPTION     
1       	Tue Feb 26 13:55:36 2019	SUPERSEDED	openebs-0.8.1	Install complete
2       	Tue Feb 26 14:21:17 2019	DEPLOYED  	openebs-0.8.1	Upgrade complete
```
```
$ kubectl logs   kube-apiserver-master-ubuntu-test -n kube-system | grep "token"
I0226 08:17:47.724646       1 storage_rbac.go:246] created role.rbac.authorization.k8s.io/system:controller:token-cleaner in kube-system
I0226 08:17:48.043648       1 storage_rbac.go:276] created rolebinding.rbac.authorization.k8s.io/system:controller:token-cleaner in kube-system
```
```
$ kubectl get pvc
NAME               STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS           AGE
percona-jd-claim   Bound     pvc-4fbec0e1-39a0-11e9-9cf6-0cc47ae54562   5G         RWO            openebs-jiva-default   68m
```
```
$ kubectl get po
NAME                                                             READY     STATUS    RESTARTS   AGE
percona-jd-7d6d9bdc54-8skxp                                      1/1       Running   0          69m
pvc-4fbec0e1-39a0-11e9-9cf6-0cc47ae54562-ctrl-6c4d7467df-m4txs   2/2       Running   0          69m
pvc-4fbec0e1-39a0-11e9-9cf6-0cc47ae54562-rep-df849cb9-2jlnf      1/1       Running   0          69m
pvc-4fbec0e1-39a0-11e9-9cf6-0cc47ae54562-rep-df849cb9-njbsz      1/1       Running   0          69m
pvc-4fbec0e1-39a0-11e9-9cf6-0cc47ae54562-rep-df849cb9-wmncl      1/1       Running   0          69m
```

**Comment by runningman84** [comment] 2019-03-02 22:48
ok I could not reproduce the error with the latest 0.8.1 release

**Comment by kmova** [comment] 2019-03-06 01:47
Thanks for trying this out @runningman84 . Will close this issue for now as not reproducible in 0.8.1

**Closed by kmova** 2019-03-06 01:47 UTC
Labels: release-note/open
