### ISSUE TITLE
[PerconaDB][Vagrant] while deploying PerconaDB in Vagrant-VM  shows CrashloopBackoff

### ISSUE THREAD

**Issue by nsathyaseelan** [openebs/openebs#1101] opened 2018-01-09 07:36 UTC
BUG REPORT 
OpenEBS version of 0.5.1
When try to deploy Percona DB in vagrant vm the pods will show the crashloopBackoff error
if i run `demo-percona-mysql-pvc.yaml` file the percona pod is in running state after  trying to run `sql-loadgen.yaml` file the percona pod will shows the crashloopbackoff error
```
ubuntu@kubemaster-01:~/openebs/k8s/demo/percona$ kubectl get pods
NAME                                                             READY     STATUS             RESTARTS   AGE
maya-apiserver-3053842955-0hnf2                                  1/1       Running            0          1h
openebs-provisioner-2499455298-c2k8q                             1/1       Running            0          1h
percona                                                          0/1       CrashLoopBackOff   19         1h
pvc-3b927848-f500-11e7-85ed-021c6f7dbe9d-ctrl-4246854988-rg9lt   2/2       Running            0          1h
pvc-3b927848-f500-11e7-85ed-021c6f7dbe9d-rep-2291527275-nfdkk    1/1       Running            0          1h
ubuntu@kubemaster-01:~/openebs/k8s/demo/percona$ kubectl describe po percona
Name:		percona
Namespace:	default
Node:		kubeminion-02/172.28.128.5
Start Time:	Tue, 09 Jan 2018 05:45:00 +0000
Labels:		name=percona
Annotations:	kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"labels":{"name":"percona"},"name":"percona","namespace":"default"},"spec":{"containers":[...
Status:		Running
IP:		10.36.0.1
Containers:
  percona:
    Container ID:	docker://9c040b0328e5af03426fae4f4b82a3315d8a2972d9042e6010ff30621c333e7c
    Image:		percona
    Image ID:		docker://sha256:dc189d65dd082c9976fa8257f3b048f02b4f02d5ea581f0de8d507378b2370d5
    Port:		3306/TCP
    Args:
      --ignore-db-dir
      lost+found
    State:		Waiting
      Reason:		CrashLoopBackOff
    Last State:		Terminated
      Reason:		Error
      Exit Code:	1
      Started:		Tue, 09 Jan 2018 07:30:57 +0000
      Finished:		Tue, 09 Jan 2018 07:30:58 +0000
    Ready:		False
    Restart Count:	19
    Limits:
      cpu:	500m
    Requests:
      cpu:	500m
    Environment:
      MYSQL_ROOT_PASSWORD:	k8sDem0
    Mounts:
      /var/lib/mysql from demo-vol1 (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-lm628 (ro)
Conditions:
  Type		Status
  Initialized 	True 
  Ready 	False 
  PodScheduled 	True 
Volumes:
  demo-vol1:
    Type:	PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:	demo-vol1-claim
    ReadOnly:	false
  default-token-lm628:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	default-token-lm628
    Optional:	false
QoS Class:	Burstable
Node-Selectors:	<none>
Tolerations:	node.alpha.kubernetes.io/notReady:NoExecute for 300s
		node.alpha.kubernetes.io/unreachable:NoExecute for 300s
Events:
  FirstSeen	LastSeen	Count	From			SubObjectPath			Type		Reason		Message
  ---------	--------	-----	----			-------------			--------	------		-------
  1h		44m		8	kubelet, kubeminion-02	spec.containers{percona}	Warning		Failed		Failed to pull image "percona": rpc error: code = 2 desc = Network timed out while trying to connect to https://index.docker.io/v1/repositories/library/percona/images. You may want to check your internet connection or if you are behind a proxy.
  1h		39m		87	kubelet, kubeminion-02	spec.containers{percona}	Normal		BackOff		Back-off pulling image "percona"
  1h		2m		28	kubelet, kubeminion-02	spec.containers{percona}	Normal		Pulling		pulling image "percona"
  1h		2m		20	kubelet, kubeminion-02	spec.containers{percona}	Normal		Pulled		Successfully pulled image "percona"
  1h		2m		20	kubelet, kubeminion-02	spec.containers{percona}	Normal		Created		Created container
  1h		2m		20	kubelet, kubeminion-02	spec.containers{percona}	Normal		Started		Started container
  1h		15s		343	kubelet, kubeminion-02	spec.containers{percona}	Warning		BackOff		Back-off restarting failed container
  1h		15s		439	kubelet, kubeminion-02					Warning		FailedSync	Error syncing pod

```

**Comment by ksatchit** [comment] 2018-03-23 14:42
@nsathyaseelan , can you please share the logs of the application, volume controller & replica pods ? Also, how many nodes did the vagrant-based cluster have ? 

Please check the following: 

- If the vagrant has a minimum of 2G of memory on the nodes 
- If there were any network loss/delays observed between the pods (app-ctrl, ctrl-rep)

In all probability, the volume have been remounted as RO, causing the application to crash. Possible duplicate of #880 

The RO issue is explained and tracked at : #1260

**Closed** 2018-03-26 02:27 UTC
Labels: openebs-hackfest
