### ISSUE TITLE
NDM creating disk CR for OpenEBS cStor volumes

### ISSUE THREAD

**Issue by vishnuitta** [openebs/openebs#2438] opened 2019-03-13 16:34 UTC
```Name:         disk-9e06708c96e31110d61025582a21ff00
Namespace:    
Labels:       kubernetes.io/hostname=k8s-slave-7
              ndm.io/disk-type=disk
              ndm.io/managed=true
Annotations:  <none>
API Version:  openebs.io/v1alpha1
Kind:         Disk
Metadata:
  Creation Timestamp:  2019-03-07T13:16:46Z
  Generation:          2
  Resource Version:    6499472
  Self Link:           /apis/openebs.io/v1alpha1/disks/disk-9e06708c96e31110d61025582a21ff00
  UID:                 423c27ef-40db-11e9-8177-0adca0f07026
Spec:
  Capacity:
    Logical Sector Size:   512
    Physical Sector Size:  0
    Storage:               10737418240
  Details:
    Compliance:         
    Drive Type:         
    Firmware Revision:  
    Model:              
    Rotation Rate:      0
    Serial:             
    Vendor:             
  Devlinks:
    Kind:  by-path
    Links:
      /dev/disk/by-path/ip-IP-MASK:3260-iscsi-iqn.2016-09.com.openebs.cstor:pvc-97bb7681-40d1-11e9-8177-0adca0f07026-lun-0
  Path:  /dev/sda
Stats:
  Device Utilization Rate:  0
  Disk Temperature:
    Current Temperature:   0
    Highest Temperature:   0
    Lowest Temperature:    0
  Percent Endurance Used:  0
  Total Bytes Read:        0
  Total Bytes Written:     0
Status:
  State:  Active
Events:   <none>```

When the Vendor is empty, disk CR is created. There may be various reason why details are not filled.

So, Disk CRs should not be created when vendor is NOT known.

**Comment by muratkars** [comment] 2019-04-05 16:47
Not able to reproduce, closing for now.

**Closed by muratkars** 2019-04-05 16:47 UTC
