### ISSUE TITLE
Fix golint issues in maya/types/v1/meta.go

### ISSUE THREAD

**Issue by rockydcoder** [openebs/openebs#2188] opened 2018-10-20 07:26 UTC
File: [maya/blob/master/types/v1/meta.go](https://github.com/openebs/maya/blob/master/types/v1/meta.go)

`Line 222: warning: exported type Labels should have comment or be unexported (golint)`
`Line 278: warning: exported const LabelSelectorOpNotIn should have comment (or a comment on this block) or be unexported (golint)`

**Comment by mathagician** [comment] 2019-10-05 07:50
@AmitKumarDas I explored this issue. The issue is already resolved. You can verifiy and close this.

**Comment by AmitKumarDas** [comment] 2019-10-05 08:05
thanks @mathagician . Will close it.

**Closed by AmitKumarDas** 2019-10-05 08:05 UTC
Labels: Hacktoberfest, maya
