### ISSUE TITLE
Unable to deploy applications in openebs provisioner v0.5.0

### ISSUE THREAD

**Issue by nsathyaseelan** [openebs/openebs#1254] opened 2018-02-20 12:03 UTC
BUG REPORT

**What happened**:
- While try to deploy cassandra in GKE thus the GKE pod is in pending state
```
kubectl get pods
NAME                                   READY     STATUS    RESTARTS   AGE
cassandra-0                            0/1       Pending   0          11m
cortex-agent-938067842-3gh63           1/1       Running   0          1h
maya-apiserver-2288016177-zfkqg        1/1       Running   0          13m
openebs-provisioner-2835097941-58g1c   1/1       Running   0          13m
```
```
kubectl get pvc
NAME                         STATUS    VOLUME    CAPACITY   ACCESS MODES   STORAGECLASS        AGE
cassandra-data-cassandra-0   Pending                                       openebs-cassandra   13m
```
```
kubectl logs -f openebs-provisioner-2835097941-58g1c
/home/travis/gopath/src/github.com/kubernetes-incubator/external-storage/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
/home/travis/gopath/src/github.com/kubernetes-incubator/external-storage/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:153
/home/travis/.gimme/versions/go1.8.3.linux.amd64/src/runtime/asm_amd64.s:514
/home/travis/.gimme/versions/go1.8.3.linux.amd64/src/runtime/panic.go:489
/home/travis/.gimme/versions/go1.8.3.linux.amd64/src/runtime/panic.go:63
/home/travis/.gimme/versions/go1.8.3.linux.amd64/src/runtime/signal_unix.go:290
/home/travis/gopath/src/github.com/kubernetes-incubator/external-storage/openebs/openebs-provisioner.go:93
/home/travis/gopath/src/github.com/kubernetes-incubator/external-storage/lib/controller/controller.go:800
/home/travis/gopath/src/github.com/kubernetes-incubator/external-storage/lib/controller/controller.go:657
/home/travis/gopath/src/github.com/kubernetes-incubator/external-storage/vendor/k8s.io/kubernetes/pkg/util/goroutinemap/goroutinemap.go:130
/home/travis/.gimme/versions/go1.8.3.linux.amd64/src/runtime/asm_amd64.s:2197
I0220 12:03:03.568466       1 controller.go:1080] scheduleOperation[provision-default/cassandra-data-cassandra-0[e4418829-1633-11e8-bf3e-42010a8000fa]]
E0220 12:03:03.568503       1 controller.go:1087] Error scheduling operaion "provision-default/cassandra-data-cassandra-0[e4418829-1633-11e8-bf3e-42010a8000fa]": Failed to create operation with name "provision-default/cassandra-data-cassandra-0[e4418829-1633-11e8-bf3e-42010a8000fa]". An operation with that name failed at 2018-02-20 12:02:48.613624462 +0000 UTC. No retries permitted until 2018-02-20 12:04:50.613624462 +0000 UTC (2m2s). Last error: "recovered from panic \"runtime error: invalid memory address or nil pointer dereference\". (err=<nil>) Call stack:\n/home/travis/gopath/src/github.com/kubernetes-incubator/external-storage/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72\n/home/travis/gopath/src/github.com/kubernetes-incubator/external-storage/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:153\n/home/travis/.gimme/versions/go1.8.3.linux.amd64/src/runtime/asm_amd64.s:514\n/home/travis/.gimme/versions/go1.8.3.linux.amd64/src/runtime/panic.go:489\n/home/travis/.gimme/versions/go1.8.3.linux.amd64/src/runtime/panic.go:63\n/home/travis/.gimme/versions/go1.8.3.linux.amd64/src/runtime/signal_unix.go:290\n/home/travis/gopath/src/github.com/kubernetes-incubator/external-storage/openebs/openebs-provisioner.go:93\n/home/travis/gopath/src/github.com/kubernetes-incubator/external-storage/lib/controller/controller.go:800\n/home/travis/gopath/src/github.com/kubernetes-incubator/external-storage/lib/controller/controller.go:657\n/home/travis/gopath/src/github.com/kubernetes-incubator/external-storage/vendor/k8s.io/kubernetes/pkg/util/goroutinemap/goroutinemap.go:130\n/home/travis/.gimme/versions/go1.8.3.linux.amd64/src/runtime/asm_amd64.s:2197\n".
```

**Comment by kmova** [comment] 2018-02-21 04:50
This issue is fixed in v0.5.1

Duplicate of https://github.com/openebs/openebs/issues/1054

**Closed by kmova** 2018-02-21 04:50 UTC
Labels: duplicate
