### ISSUE TITLE
waitForFirstConsumer PVCs fail to bind when Pod spec.nodeName is specified

### ISSUE THREAD

**Issue by ppodolsky** [openebs/openebs#2915] opened 2020-02-15 21:29 UTC
## Description
PVC creation does not lead to creation of PV in LocalPV. The bug is related to kube control plane, which is not setting proper annotations on PVC. It looks like a race condition, because sometimes it provisions and sometimes does not. Much more details are in the discussion with @kmova in OpenEBS Slack.

## Expected Behavior
PV is created consistently every time.

## Current Behavior
Deployment of the statefulset with volumeClaimTemplate leads to a creation of PVC, but localpv doesn't get any request to provision volume due to unknown troubles in the kubernetes control plane.

## Your Environment

* `statefulset config.yaml`
```
  volumeClaimTemplates:
    - metadata:
        name: storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 30Gi
        storageClassName: openebs-hostpath
```
* `kubectl get pods`:
```
pasha@host:~ kubectl get pods
NAME                              READY   STATUS              RESTARTS   AGE
mail-0                            0/4     ContainerCreating   0          62m
```
* `kubectl get pvc`:
```
pasha@host:~ kubectl get pvc
NAME                         STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   
storage-mail-0               Pending                                                                        openebs-hostpath           12h
```
* OS (from `/etc/os-release`): 19.10 (Eoan Ermine) both on the control plane node and on worker nodes.
* Kernel (from `uname -a`): 5.3.0-29-generic

All openebs components are set and going well.

**Comment by kmova** [comment] 2020-04-01 17:43
@ppodolsky mentioned that the issue has been narrowed down to a case of Statefulset containing a nodeAffinity being set. 

```
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - node-name
```

**Comment by kmova** [comment] 2020-04-05 13:23
Attempted to reproduce the issue with above nodeAffinity spec on GKE. A 3 replica statefulset resulted in scheduling all 3 replicas on to the same specified node. Am still unable to reproduce the issue.

**Comment by ppodolsky** [comment] 2020-04-20 16:02
I just stucked to it again. Everything was OK when I had pointed affinity by a `nodeAffinity` attribute, but failed when I had pinned the node by old plain `nodeName` (`.spec.nodeName`)

**Comment by kmova** [comment] 2020-05-03 16:22
@ppodolsky  `pod.spec.nodeName`  is indeed the root cause. For your use case, could you move away from using nodeName and instead use nodeAffinity. 

---

Here is the reason for volumes not getting created when nodeName is used. 

The hostpath volumes are created using the `waitForFirstConsumer`. This involves a handshake between the pod scheduler and the volume controller for creating volumes. 

- The Volume controller will wait, till the pods using the PVC has been scheduled. The [controller waits](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/volume/scheduling/scheduler_binder.go#L281) for the scheduler to set an annotation on PVC with the selected node. 
- The scheduler, after finding a suitable node, will [update the PVC with the annotation of selected node](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/scheduler.go#L627).

The [scheduler has two queues](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/eventhandlers.go#L353); an `unscheduled pods queue` and `scheduled pods queue`. The above logic of assigning the pods and updating the PVC annotations is done when pods are added to `unscheduled pods queue`. After assigning the node to the pod, the pod is moved to `scheduled pod queue`. 

When Pod spec contains a `nodeName`, the scheduler skips the `unscheduled pods queue` and adds directly to [scheduled pods queue](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/eventhandlers.go#L358).  This causes, the Volume controller to never start binding of the PVC. The following logs keep repeating in the `kube-controller-manager` pod. 

```
I0503 16:12:10.049967       1 event.go:278] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"demo-local-hostpath-busybox-sts-local-hostpath-0", UID:"7f06a345-8551-4f07-bafa-9cad87ace6d1", APIVersion:"v1", ResourceVersion:"2914960", FieldPath:""}): type: 'Normal' reason: 'WaitForFirstConsumer' waiting for first consumer to be created before binding
I0503 16:12:25.050080       1 event.go:278] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"demo-local-hostpath-busybox-sts-local-hostpath-0", UID:"7f06a345-8551-4f07-bafa-9cad87ace6d1", APIVersion:"v1", ResourceVersion:"2914960", FieldPath:""}): type: 'Normal' reason: 'WaitForFirstConsumer' waiting for first consumer to be created before binding
```

The `kubectl describe pod` will also directly start showing the unbound volume events from kubelet instead of events from scheduler:

When scheduler gets involved, the following events will be seen:
```
Events:
  Type     Reason       Age                    From               Message
  ----     ------       ----                   ----               -------
  Warning  FailedMount  7m6s (x82 over 87m)    kubelet, kiran-w1  Unable to attach or mount volumes: unmounted volumes=[demo-local-hostpath], unattached volumes=[default-token-dsgtt demo-local-hostpath]: error processing PVC default/demo-local-hostpath-busybox-sts-local-hostpath-0: PVC is not bound
  Warning  FailedMount  2m17s (x302 over 87m)  kubelet, kiran-w1  Unable to attach or mount volumes: unmounted volumes=[demo-local-hostpath], unattached volumes=[demo-local-hostpath default-token-dsgtt]: error processing PVC default/demo-local-hostpath-busybox-sts-local-hostpath-0: PVC is not bound
```

---

When nodeName is not used and volumes are provisioned successfully, the pod events will start with `scheduler` trying to assign the node as follows:

```
Events:
  Type     Reason            Age                From               Message
  ----     ------            ----               ----               -------
  Warning  FailedScheduling  15s (x2 over 15s)  default-scheduler  persistentvolumeclaim "demo-vol1-claim" not found
  Normal   Scheduled         6s                 default-scheduler  Successfully assigned default/busybox to kiran-w2
```

Once the scheduler has assigned the node, the PVC also will have an annotation like:
```
     volume.kubernetes.io/selected-node: kiran-w2
```

**Comment by ppodolsky** [comment] 2020-05-03 18:29
Here is an entire film plot you've uncovered:) I read it all, I like to know how about all these internal things work.

> For your use case, could you move away from using nodeName and instead use nodeAffinity.

Year, sure, I've already switched all specs to the `nodeAffinity`. 

I hope the report helped you in a some way. Personally I haven't faced with conditions of nodeName being unavoidable so probably the solution for the issue is just to point this behavior in docs. But I would leave the descision on your behalf:) Thank you!

**Comment by kmova** [comment] 2020-05-04 04:44
Makes sense to add a note in the docs before closing this issue. Also, checking with K8s-sig storage if we should do the same in K8s docs. This is a generic issue impacting any kind of volume using waitforfirstconsumer with nodeName. 

This was definitely useful for me, I know a little more about K8s now! Thank you for raising this issue and following up!

**Closed** 2020-06-02 07:45 UTC
Labels: local-pv, project/community, release-note/closed
