### ISSUE TITLE
pvc-replica not able to register with controller.

### ISSUE THREAD

**Issue by atulabhi** [openebs/openebs#1589] opened 2018-06-04 14:00 UTC
## Is this a BUG REPORT or FEATURE REQUEST?
 
 **BUG REPORT**

**What happened**:
 I have upgraded  openebs from 0.5.1 to 0.5.4. And the monitoring is not enabled in my storage class so 
 I was trying to enable it by using the following patch yaml.
 ```{
  "spec": {
     "selector": {
        "matchLabels": {
           "monitoring": "volume_exporter_prometheus"
        }
     },
     "template": {
        "metadata": {
           "labels": {
              "monitoring": "volume_exporter_prometheus"
           }
        },
        "spec": {
           "containers":[
              {
                "args": [
                   "-c=volname-ctrl-svc:9501"
                ],
                "command": [
                   "maya-volume-exporter"
                ],
                "image": "openebs/m-exporter:0.5.4",
                "imagePullPolicy": "IfNotPresent",
                "name": "maya-volume-exporter",
                "ports": [
                   {
                      "containerPort": 9500,
                      "protocol": "TCP"
                   }
                ],
                "resources": {},
                "terminationMessagePath": "/dev/termination-log",
                "terminationMessagePolicy": "File"
              }
           ] 
        }
     }
```
 After applying the yaml I got a new controller and my old controller was also running . 
![image](https://user-images.githubusercontent.com/30014772/40914522-251a34b0-6816-11e8-831d-05da6e4599ac.png)
*Output of kubectl get rs:-*
![image](https://user-images.githubusercontent.com/30014772/40914592-6ed68d7e-6816-11e8-876d-830017336c81.png)

So I deleted the replicaset of previous controller and previous controller is gone.

**What you expected to happen**:
The replica set should start communicating with the new controller.But I am getting this when i am checking the controller log ```time="2018-06-04T11:00:21Z" level=error msg="Error in request: Replica must be closed, Can not add in state: open"
time="2018-06-04T11:00:23Z" level=info msg="Connecting to remote: 10.12.26.24:9502" ```

**How to reproduce it (as minimally and precisely as possible)**:
1.Apply openebs-operator.yaml with openebs version 0.5.1.
2.Remove ```  openebs.io/volume-monitor: "true"``` from the storageclass yaml.
3.Apply the storageclass yaml.
4. Upgarde openebs to 0.5.4.
5.Now use the above patch yaml to enable monitoring.
6.Delete the old controller replicaset and check the log of new controller.

**Anything else we need to know?**:
log of controller:-
```
mount: special device /host/dev does not exist
time="2018-06-04T10:24:33Z" level=info msg="Listening on :9501" 
STATE = closed
10.12.27.27 - - [04/Jun/2018:10:27:27 +0000] "POST /v1/register HTTP/1.1" 200 0
STATE = closed
10.12.26.24 - - [04/Jun/2018:10:27:27 +0000] "POST /v1/register HTTP/1.1" 200 0
10.12.28.50 - - [04/Jun/2018:10:27:27 +0000] "POST /v1/register HTTP/1.1" 200 0
time="2018-06-04T10:27:27Z" level=info msg="Connecting to remote: 10.12.27.27:9502" 
time="2018-06-04T10:27:27Z" level=info msg="Opening: 10.12.27.27:9502" 
time="2018-06-04T10:27:27Z" level=info msg="Adding backend: tcp://10.12.27.27:9502" 
time="2018-06-04T10:27:27Z" level=info msg="Set replica tcp://10.12.27.27:9502 to mode RW" 
time="2018-06-04T10:27:27Z" level=info msg="Start monitoring tcp://10.12.27.27:9502" 
time="2018-06-04T10:27:27Z" level=info msg="Get backend tcp://10.12.27.27:9502 revision counter 2200" 
time="2018-06-04T10:27:27Z" level=info msg="SCSI device created" 
time="2018-06-04T10:27:27Z" level=info msg="Listening ..." 
time="2018-06-04T10:27:27Z" level=info msg="Connecting to remote: 10.12.26.24:9502" 
10.12.27.27 - - [04/Jun/2018:10:27:27 +0000] "POST /v1/volumes/cHZjLTZiNjgwMjM2LTY3ZGUtMTFlOC1iMjE2LTQyMDEwYTgwMDM4Zg==?action=start HTTP/1.1" 200 635
time="2018-06-04T10:27:27Z" level=info msg="Connecting to remote: 10.12.28.50:9502" 
time="2018-06-04T10:27:27Z" level=info msg="Opening: 10.12.28.50:9502" 
time="2018-06-04T10:27:27Z" level=info msg="Opening: 10.12.26.24:9502" 
time="2018-06-04T10:27:27Z" level=info msg="Snapshot: 10.12.27.27:9502 839b646c-751a-4620-9fa6-97e13a85ee52 UserCreated false Created at 2018-06-04T10:27:27Z" 
time="2018-06-04T10:27:27Z" level=info msg="Snapshot: 10.12.28.50:9502 839b646c-751a-4620-9fa6-97e13a85ee52 UserCreated false Created at 2018-06-04T10:27:27Z" 
time="2018-06-04T10:27:27Z" level=info msg="Adding backend: tcp://10.12.28.50:9502" 
time="2018-06-04T10:27:27Z" level=info msg="Start monitoring tcp://10.12.28.50:9502" 
10.12.28.50 - - [04/Jun/2018:10:27:27 +0000] "POST /v1/replicas HTTP/1.1" 200 427
time="2018-06-04T10:27:27Z" level=error msg="Error in request: Can only have one WO replica at a time" 
10.12.26.24 - - [04/Jun/2018:10:27:27 +0000] "POST /v1/replicas HTTP/1.1" 500 184
10.12.28.50 - - [04/Jun/2018:10:27:27 +0000] "GET /v1/replicas/dGNwOi8vMTAuMTIuMjguNTA6OTUwMg== HTTP/1.1" 200 427
time="2018-06-04T10:27:27Z" level=info msg="Set revision counter of 10.12.28.50:9502 to : 0" 
time="2018-06-04T10:27:27Z" level=info msg="Set backend tcp://10.12.28.50:9502 revision counter to 0" 
time="2018-06-04T10:27:27Z" level=info msg="Synchronizing volume-head-003.img.meta to volume-head-003.img.meta@10.12.28.50:9703" 
time="2018-06-04T10:27:27Z" level=info msg="Done synchronizing volume-head-003.img.meta to volume-head-003.img.meta@10.12.28.50:9703" 
10.12.28.50 - - [04/Jun/2018:10:27:27 +0000] "POST /v1/replicas/dGNwOi8vMTAuMTIuMjguNTA6OTUwMg==?action=preparerebuild HTTP/1.1" 200 342
time="2018-06-04T10:27:29Z" level=error msg="Error in request: Can only have one WO replica at a time" 
10.12.26.24 - - [04/Jun/2018:10:27:29 +0000] "POST /v1/replicas HTTP/1.1" 500 184
time="2018-06-04T10:27:31Z" level=error msg="Error in request: Can only have one WO replica at a time" 
10.12.26.24 - - [04/Jun/2018:10:27:31 +0000] "POST /v1/replicas HTTP/1.1" 500 184
time="2018-06-04T10:27:33Z" level=error msg="Error in request: Can only have one WO replica at a time" 
10.12.26.24 - - [04/Jun/2018:10:27:33 +0000] "POST /v1/replicas HTTP/1.1" 500 184
time="2018-06-04T10:27:35Z" level=error msg="Error in request: Can only have one WO replica at a time" 
10.12.26.24 - - [04/Jun/2018:10:27:35 +0000] "POST /v1/replicas HTTP/1.1" 500 184
time="2018-06-04T10:27:37Z" level=error msg="Error in request: Can only have one WO replica at a time" 
10.12.26.24 - - [04/Jun/2018:10:27:37 +0000] "POST /v1/replicas HTTP/1.1" 500 184
time="2018-06-04T10:27:38Z" level=info msg="10.12.27.28:3260" 
time="2018-06-04T10:27:38Z" level=info msg="Accepting ..." 
time="2018-06-04T10:27:38Z" level=info msg="connection is connected from 10.128.0.4:42996...\n" 
time="2018-06-04T10:27:38Z" level=info msg="Listening ..." 
time="2018-06-04T10:27:38Z" level=info msg="New Session initiator name:iqn.1993-08.org.debian:01:415c7bf392,target name:iqn.2016-09.com.openebs.jiva:pvc-6b680236-67de-11e8-b216-42010a80038f,ISID:0x23d040000" 
time="2018-06-04T10:27:39Z" level=error msg="Error in request: Can only have one WO replica at a time" 
10.12.26.24 - - [04/Jun/2018:10:27:39 +0000] "POST /v1/replicas HTTP/1.1" 500 184
10.12.26.24 - - [04/Jun/2018:10:27:41 +0000] "POST /v1/replicas HTTP/1.1" 500 184
time="2018-06-04T10:27:41Z" level=error msg="Error in request: Can only have one WO replica at a time" 
time="2018-06-04T10:27:43Z" level=error msg="Error in request: Can only have one WO replica at a time" 
10.12.26.24 - - [04/Jun/2018:10:27:43 +0000] "POST /v1/replicas HTTP/1.1" 500 184
10.12.28.50 - - [04/Jun/2018:10:27:44 +0000] "GET /v1/replicas/dGNwOi8vMTAuMTIuMjguNTA6OTUwMg== HTTP/1.1" 200 427
time="2018-06-04T10:27:44Z" level=info msg="Get backend tcp://10.12.27.27:9502 revision counter 2200" 
time="2018-06-04T10:27:44Z" level=info msg="Set revision counter of 10.12.28.50:9502 to : 2200" 
time="2018-06-04T10:27:44Z" level=info msg="Set backend tcp://10.12.28.50:9502 revision counter to 2200" 
time="2018-06-04T10:27:44Z" level=info msg="Set replica tcp://10.12.28.50:9502 to mode RW" 
time="2018-06-04T10:27:44Z" level=info msg="Update peer details of 10.12.28.50:9502 " 
time="2018-06-04T10:27:44Z" level=info msg="Update peer details of 10.12.27.27:9502 " 
10.12.28.50 - - [04/Jun/2018:10:27:44 +0000] "POST /v1/replicas/dGNwOi8vMTAuMTIuMjguNTA6OTUwMg==?action=verifyrebuild HTTP/1.1" 200 427
time="2018-06-04T10:27:45Z" level=info msg="Connecting to remote: 10.12.26.24:9502" 
time="2018-06-04T10:27:45Z" level=error msg="Error in request: Replica must be closed, Can not add in state: open" 
10.12.26.24 - - [04/Jun/2018:10:27:45 +0000] "POST /v1/replicas HTTP/1.1" 500 196
time="2018-06-04T10:27:47Z" level=info msg="Connecting to remote: 10.12.26.24:9502" 
time="2018-06-04T10:27:47Z" level=error msg="Error in request: Replica must be closed, Can not add in state: open" 
10.12.26.24 - - [04/Jun/2018:10:27:47 +0000] "POST /v1/replicas HTTP/1.1" 500 196
time="2018-06-04T10:27:49Z" level=info msg="Connecting to remote: 10.12.26.24:9502" 
time="2018-06-04T10:27:49Z" level=error msg="Error in request: Replica must be closed, Can not add in state: open" 
10.12.26.24 - - [04/Jun/2018:10:27:49 +0000] "POST /v1/replicas HTTP/1.1" 500 196
time="2018-06-04T10:27:51Z" level=info msg="Connecting to remote: 10.12.26.24:9502" 
time="2018-06-04T10:27:51Z" level=error msg="Error in request: Replica must be closed, Can not add in state: open" 
```
replica log:
```
time="2018-06-04T10:02:43Z" level=info msg="Creating volume /openebs, size 10737418240/512" 
time="2018-06-04T10:02:43Z" level=info msg="Listening on data 10.12.26.24:9503" 
time="2018-06-04T10:02:43Z" level=info msg="Listening on control 10.12.26.24:9502" 
time="2018-06-04T10:02:43Z" level=info msg="Listening on sync 10.12.26.24:9504" 
time="2018-06-04T10:03:18Z" level=info msg="Removing Replica" 
time="2018-06-04T10:03:23Z" level=info msg="Adding replica tcp://10.12.26.24:9502 in WO mode" 
time="2018-06-04T10:03:23Z" level=info msg="New connection from: 10.12.28.49:41454" 
time="2018-06-04T10:03:23Z" level=info msg="Opening volume /openebs, size 10737418240/512" 
10.12.28.49 - - [04/Jun/2018:10:03:23 +0000] "POST /v1/replicas/1?action=open HTTP/1.1" 200 1468
time="2018-06-04T10:03:23Z" level=info msg="Snapshotting [1809798a-59bc-46bc-ab05-e19aef4e5001] volume, user created false, created time 2018-06-04T10:03:23Z" 
10.12.28.49 - - [04/Jun/2018:10:03:23 +0000] "POST /v1/replicas/1?action=snapshot HTTP/1.1" 200 1786
time="2018-06-04T10:03:23Z" level=info msg="Using replica tcp://10.12.27.27:9502 as the source for rebuild " 
time="2018-06-04T10:03:23Z" level=info msg="Using replica tcp://10.12.26.24:9502 as the target for rebuild " 
10.12.26.24 - - [04/Jun/2018:10:03:23 +0000] "POST /v1/replicas/1?action=setrebuilding HTTP/1.1" 200 1585
10.12.28.49 - - [04/Jun/2018:10:03:23 +0000] "POST /v1/replicas/1?action=setrevisioncounter HTTP/1.1" 200 1585
time="2018-06-04T10:03:23Z" level=info msg="Running ssync [ssync -port 9700 -daemon volume-head-001.img.meta]" 
time="2018-06-04T10:03:23Z" level=info msg="Creating Ssync service" 
time="2018-06-04T10:03:23Z" level=info msg="open: receiving fileSize: 164, setting up directIo: false" 
time="2018-06-04T10:03:23Z" level=info msg="Ssync server opened and ready" 
time="2018-06-04T10:03:23Z" level=info msg="Ssync server exit(0)" 
time="2018-06-04T10:03:23Z" level=info msg="Done running ssync [ssync -port 9700 -daemon volume-head-001.img.meta]" 
time="2018-06-04T10:03:23Z" level=info msg="Synchronizing volume-snap-1809798a-59bc-46bc-ab05-e19aef4e5001.img to volume-snap-1809798a-59bc-46bc-ab05-e19aef4e5001.img@10.12.26.24:9701" 
time="2018-06-04T10:03:23Z" level=info msg="Running ssync [ssync -port 9701 -daemon volume-snap-1809798a-59bc-46bc-ab05-e19aef4e5001.img]" 
time="2018-06-04T10:03:23Z" level=info msg="Creating Ssync service" 
time="2018-06-04T10:03:23Z" level=info msg="open: receiving fileSize: 10737418240, setting up directIo: true" 
time="2018-06-04T10:03:23Z" level=info msg="Ssync server opened and ready" 
time="2018-06-04T10:03:23Z" level=info msg="Ssync server exit(0)" 
time="2018-06-04T10:03:23Z" level=info msg="Done running ssync [ssync -port 9701 -daemon volume-snap-1809798a-59bc-46bc-ab05-e19aef4e5001.img]" 
time="2018-06-04T10:03:23Z" level=info msg="Done synchronizing volume-snap-1809798a-59bc-46bc-ab05-e19aef4e5001.img to volume-snap-1809798a-59bc-46bc-ab05-e19aef4e5001.img@10.12.26.24:9701" 
time="2018-06-04T10:03:23Z" level=info msg="Synchronizing volume-snap-1809798a-59bc-46bc-ab05-e19aef4e5001.img.meta to volume-snap-1809798a-59bc-46bc-ab05-e19aef4e5001.img.meta@10.12.26.24:9702" 
time="2018-06-04T10:03:23Z" level=info msg="Running ssync [ssync -port 9702 -daemon volume-snap-1809798a-59bc-46bc-ab05-e19aef4e5001.img.meta]" 
time="2018-06-04T10:03:23Z" level=info msg="Creating Ssync service" 
time="2018-06-04T10:03:23Z" level=info msg="open: receiving fileSize: 164, setting up directIo: false" 
time="2018-06-04T10:03:23Z" level=info msg="Ssync server opened and ready" 
time="2018-06-04T10:03:23Z" level=info msg="Ssync server exit(0)" 
time="2018-06-04T10:03:23Z" level=info msg="Done running ssync [ssync -port 9702 -daemon volume-snap-1809798a-59bc-46bc-ab05-e19aef4e5001.img.meta]" 
time="2018-06-04T10:03:23Z" level=info msg="Done synchronizing volume-snap-1809798a-59bc-46bc-ab05-e19aef4e5001.img.meta to volume-snap-1809798a-59bc-46bc-ab05-e19aef4e5001.img.meta@10.12.26.24:9702" 
time="2018-06-04T10:03:23Z" level=info msg="Synchronizing volume-snap-1ec765c9-9107-4359-a86c-35a0ac31d77e.img to volume-snap-1ec765c9-9107-4359-a86c-35a0ac31d77e.img@10.12.26.24:9703" 
time="2018-06-04T10:03:23Z" level=info msg="Running ssync [ssync -port 9703 -daemon volume-snap-1ec765c9-9107-4359-a86c-35a0ac31d77e.img]" 
time="2018-06-04T10:03:23Z" level=info msg="Creating Ssync service" 
time="2018-06-04T10:03:23Z" level=info msg="open: receiving fileSize: 10737418240, setting up directIo: true" 
time="2018-06-04T10:03:23Z" level=info msg="Ssync server opened and ready" 
time="2018-06-04T10:03:23Z" level=info msg="Ssync server exit(0)" 
time="2018-06-04T10:03:23Z" level=info msg="Done running ssync [ssync -port 9703 -daemon volume-snap-1ec765c9-9107-4359-a86c-35a0ac31d77e.img]" 
time="2018-06-04T10:03:24Z" level=info msg="Done synchronizing volume-snap-1ec765c9-9107-4359-a86c-35a0ac31d77e.img to volume-snap-1ec765c9-9107-4359-a86c-35a0ac31d77e.img@10.12.26.24:9703" 
time="2018-06-04T10:03:24Z" level=info msg="Synchronizing volume-snap-1ec765c9-9107-4359-a86c-35a0ac31d77e.img.meta to volume-snap-1ec765c9-9107-4359-a86c-35a0ac31d77e.img.meta@10.12.26.24:9704" 
time="2018-06-04T10:03:24Z" level=info msg="Running ssync [ssync -port 9704 -daemon volume-snap-1ec765c9-9107-4359-a86c-35a0ac31d77e.img.meta]" 
time="2018-06-04T10:03:24Z" level=info msg="Creating Ssync service" 
time="2018-06-04T10:03:24Z" level=info msg="open: receiving fileSize: 112, setting up directIo: false" 
time="2018-06-04T10:03:24Z" level=info msg="Ssync server opened and ready" 
time="2018-06-04T10:03:24Z" level=info msg="Ssync server exit(0)" 
time="2018-06-04T10:03:24Z" level=info msg="Done running ssync [ssync -port 9704 -daemon volume-snap-1ec765c9-9107-4359-a86c-35a0ac31d77e.img.meta]" 
time="2018-06-04T10:03:24Z" level=info msg="Done synchronizing volume-snap-1ec765c9-9107-4359-a86c-35a0ac31d77e.img.meta to volume-snap-1ec765c9-9107-4359-a86c-35a0ac31d77e.img.meta@10.12.26.24:9704" 
time="2018-06-04T10:03:24Z" level=info msg="Reloading volume" 
10.12.26.24 - - [04/Jun/2018:10:03:24 +0000] "POST /v1/replicas/1?action=reload HTTP/1.1" 200 1971
10.12.28.49 - - [04/Jun/2018:10:03:24 +0000] "POST /v1/replicas/1?action=setrevisioncounter HTTP/1.1" 200 1971
10.12.28.49 - - [04/Jun/2018:10:03:24 +0000] "POST /v1/replicas/1?action=updatepeerdetails HTTP/1.1" 200 1971
10.12.26.24 - - [04/Jun/2018:10:03:24 +0000] "POST /v1/replicas/1?action=setrebuilding HTTP/1.1" 200 2172
time="2018-06-04T10:27:27Z" level=info msg="Closing volume" 
10.12.28.49 - - [04/Jun/2018:10:27:27 +0000] "POST /v1/replicas/1?action=close HTTP/1.1" 200 963
time="2018-06-04T10:27:27Z" level=info msg="Removing Replica" 
time="2018-06-04T10:27:27Z" level=info msg="Adding replica tcp://10.12.26.24:9502 in WO mode" 
10.12.27.28 - - [04/Jun/2018:10:27:27 +0000] "POST /v1/replicas/1?action=start HTTP/1.1" 200 963
time="2018-06-04T10:27:27Z" level=info msg="New connection from: 10.12.27.28:47804" 
time="2018-06-04T10:27:27Z" level=info msg="Opening volume /openebs, size 10737418240/512" 
10.12.27.28 - - [04/Jun/2018:10:27:27 +0000] "POST /v1/replicas/1?action=open HTTP/1.1" 200 2270
time="2018-06-04T10:27:29Z" level=info msg="Adding replica tcp://10.12.26.24:9502 in WO mode" 
time="2018-06-04T10:27:31Z" level=info msg="Adding replica tcp://10.12.26.24:9502 in WO mode" 
time="2018-06-04T10:27:33Z" level=info msg="Adding replica tcp://10.12.26.24:9502 in WO mode" 
time="2018-06-04T10:27:35Z" level=info msg="Adding replica tcp://10.12.26.24:9502 in WO mode" 
time="2018-06-04T10:27:37Z" level=info msg="Adding replica tcp://10.12.26.24:9502 in WO mode" 
time="2018-06-04T10:27:39Z" level=info msg="Adding replica tcp://10.12.26.24:9502 in WO mode" 
time="2018-06-04T10:27:41Z" level=info msg="Adding replica tcp://10.12.26.24:9502 in WO mode" 
time="2018-06-04T10:27:43Z" level=info msg="Adding replica tcp://10.12.26.24:9502 in WO mode" 
time="2018-06-04T10:27:45Z" level=info msg="Adding replica tcp://10.12.26.24:9502 in WO mode" 
time="2018-06-04T10:27:47Z" level=info msg="Adding replica tcp://10.12.26.24:9502 in WO mode" 
time="2018-06-04T10:27:49Z" level=info msg="Adding replica tcp://10.12.26.24:9502 in WO mode" 
time="2018-06-04T10:27:51Z" level=info msg="Adding replica tcp://10.12.26.24:9502 in WO mode" 
```
other required files:
volume-snap-1ec765c9-9107-4359-a86c-35a0ac31d77e.img.meta
```
{"Name":"volume-head-000.img","Parent":"","Removed":false,"UserCreated":false,"Created":"2018-06-04T10:03:18Z"}
```
volume-snap-1809798a-59bc-46bc-ab05-e19aef4e5001.img.meta
```
{"Name":"volume-head-001.img","Parent":"volume-snap-1ec765c9-9107-4359-a86c-35a0ac31d77e.img","Removed":false,"UserCreated":false,"Created":"2018-06-04T10:03:23Z"}
```
volume.meta
```
{"Size":10737418240,"Head":"volume-head-003.img","Dirty":true,"Rebuilding":false,"Parent":"volume-snap-839b646c-751a-4620-9fa6-97e13a85ee52.img","SectorSize":512,"BackingFileName":""}
```
volume-head-003.img.meta
```
{"Name":"volume-head-003.img","Parent":"volume-snap-839b646c-751a-4620-9fa6-97e13a85ee52.img","Removed":false,"UserCreated":false,"Created":"2018-06-04T10:27:27Z"}
```
volume-snap-839b646c-751a-4620-9fa6-97e13a85ee52.img.meta
```
{"Name":"volume-head-002.img","Parent":"volume-snap-1809798a-59bc-46bc-ab05-e19aef4e5001.img","Removed":false,"UserCreated":false,"Created":"2018-06-04T10:27:27Z"}
```

**Comment by ksatchit** [comment] 2018-06-19 09:40
This is a duplicate of  https://github.com/openebs/openebs/issues/1084

**Closed** 2018-06-19 09:51 UTC
