### ISSUE TITLE
Tutorial for Architecture and components

### ISSUE THREAD

**Issue by nsathyaseelan** [openebs/openebs#841] opened 2017-11-03 07:01 UTC
FEATURE REQUEST

**What happened**:

**What you expected to happen**:
Create Tutorial for Architecture and components of OpenEBS
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by ksatchit** [comment] 2018-03-23 12:38
Duplicate of https://github.com/openebs/openebs/issues/839

**Closed** 2019-12-16 00:10 UTC
Labels: docs, no-issue-activity, summerhack
