### ISSUE TITLE
Jiva PV is marked as created before the volume is fully initialized

### ISSUE THREAD

**Issue by yelhouti** [openebs/openebs#3395] opened 2021-05-16 21:40 UTC
## Description

When I use jiva, my pod sporadically emits an event with the following error on startup:
```
MountVolume.MountDevice failed for volume "pvc-839ce3ed-0812-438b-b939-7ba64d3b5643" : rpc error: code = Internal desc = failed to find device path: [], last error seen: failed to sendtargets to portal 10.233.9.161:3260, err: iscsiadm error: iscsiadm: cannot make connection to 10.233.9.161: Connection refusediscsiadm: cannot make connection to 10.233.9.161: Connection refusediscsiadm: cannot make connection to 10.233.9.161: Connection refusediscsiadm: cannot make connection to 10.233.9.161: Connection refusediscsiadm: cannot make connection to 10.233.9.161: Connection refusediscsiadm: cannot make connection to 10.233.9.161: Connection refusediscsiadm: connection login retries (reopen_max) 5 exceedediscsiadm: Could not perform SendTargets discovery: iSCSI PDU timed out (exit status 11)
```
After that, it seems like it worked.
## Expected Behavior
Do not show erroe

**Comment by kmova** [comment] 2021-05-17 09:27
There are a couple of options we should explore on this one: 
- Setup wait during the creation time to create PV - only when volumes is ready. 
- Check if using the volume health CSI api will resolve this for both create and re-mount cases.

**Comment by shubham14bajpai** [comment] 2021-05-17 10:07
I was trying to reproduce the error but was not successful 

```
Events:
  Type     Reason            Age                   From               Message
  ----     ------            ----                  ----               -------
  Warning  FailedScheduling  7m59s                 default-scheduler  0/1 nodes are available: 1 pod has unbound immediate PersistentVolumeClaims.
  Warning  FailedScheduling  7m59s                 default-scheduler  0/1 nodes are available: 1 pod has unbound immediate PersistentVolumeClaims.
  Normal   Scheduled         7m57s                 default-scheduler  Successfully assigned default/fio-67ff56bc54-lphz8 to 127.0.0.1
  Warning  FailedMount       2m16s (x3 over 6m3s)  kubelet            MountVolume.MountDevice failed for volume "pvc-e45d1c32-172c-4287-aed2-b886c49319ed" : rpc error: code = FailedPrecondition desc = Max retry count exceeded, volume: {pvc-e45d1c32-172c-4287-aed2-b886c49319ed} is not ready
  Warning  FailedMount       80s (x3 over 5m54s)   kubelet            Unable to attach or mount volumes: unmounted volumes=[fio-vol], unattached volumes=[fio-vol default-token-kwrtt]: timed out waiting for the condition
  Normal   Pulling           25s                   kubelet            Pulling image "openebs/tests-fio"
  Normal   Pulled            8s                    kubelet            Successfully pulled image "openebs/tests-fio" in 17.450105824s
  Normal   Created           1s                    kubelet            Created container perfrunner
  Normal   Started           0s                    kubelet            Started container perfrunner
```
I halted the jiva replica sts scheduling by deleting the `openebs-hostpath` storageclass. Then applied the storageclass again after 5 minutes.
As we can see from the  events and its timestamps that jiva-csi already has the checks for non ready volumes.

Another way I think it may occur is that the volume becomes ready and goes down due to some other issue just before mounting. 

@yelhouti Can you provide your setup details like the k8s version and how it was setup. That can help us with reproducing this error.

**Comment by yelhouti** [comment] 2021-05-17 18:28
@shubham14bajpai thanks for investigation I am using k8s 19.X installed using kubespray, a soon as I encoutner the issue again I will post here (I didn't manage to reproduce myself)

**Comment by kmova** [comment] 2021-08-15 16:07
@yelhouti - will close this for now. We can re-open if the issue re-appears.

**Closed by kmova** 2021-08-15 16:07 UTC
